### ISSUE TITLE
Apple Watch Support

### ISSUE THREAD

**Issue by renzska** [xamarin/Essentials#271] opened 2018-05-25 16:22 UTC
### Description

Apple Watch Apps not supported

### Steps to Reproduce

1. Create an Apple Watch App
2. Reference Xamarin.Essentials
3. Use a feature (Preferences, in my case) of Xamarin.Essentials in your Apple Watch App

### Expected Behavior

The feature works where there is an equivalent in Apple Watch to iOS

### Actual Behavior

Crashes: Could not find `Xamarin.Essentials` referenced by assembly `MyTestApp.iOS.WatchExtension, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null`.

### Basic Information

I'm creating this issue to see what the future plans are for supporting the Apple Watch.

**Comment by prashantvc** [comment] 2018-05-29 05:38
This is rather strange! I am not able to reproduce this with v0.6-preview
Could you share a small sample demonstrating the problem?

**Comment by jamesmontemagno** [comment] 2018-06-04 16:27
So, this is correct, Essentials does not support Apple Watch at this time. When you install it into a non-supported platform you will be getting the .NET Standard version which does not have any implementation.

**Comment by dais-set** [comment] 2018-07-20 09:02
Hi, we have also hit the same issue. Would you consider adding support for apple watch for the Secure Storage plugin?
We can confirm the iOS implementation uses the same classes. (I decompiled the Xamarin.WatchOS and verified all classes exist). Currently we copied your iOS implementation to the watchOS Extension project and we use it successfully.
Thanks!

**Comment by beeradmoore** [comment] 2018-10-01 23:06
So I needed to use Xamarin.Essentials in a watch project and found that this is broken. I tried to modify the csproj to add support for WatchOS, starting with adding the TargetFramework.

`   <TargetFrameworks Condition=" '$(OS)' == 'Windows_NT' ">netstandard1.0;netstandard2.0;Xamarin.iOS10;Xamarin.WatchOS10;MonoAndroid71;MonoAndroid80;MonoAndroid81;uap10.0.16299</TargetFrameworks>
    <TargetFrameworks Condition=" '$(OS)' != 'Windows_NT' ">netstandard1.0;netstandard2.0;Xamarin.iOS10;Xamarin.WatchOS10;MonoAndroid71;MonoAndroid80;MonoAndroid81;</TargetFrameworks>
`

I am unsure what the correct target framework is for WatchOS. I checked in my Xamarin.WatchOS.App.CSharp.targets file to see that the target framework and version is in the same structure as iOS.

`		<TargetFrameworkIdentifier Condition="'$(TargetFrameworkIdentifier)' == ''">Xamarin.WatchOS</TargetFrameworkIdentifier>
		<TargetFrameworkVersion Condition="'$(TargetFrameworkVersion)' == ''">v1.0</TargetFrameworkVersion>` 

But this does not compile, it gives the error of 


> "/Users/bradmoore/git/Essentials/Xamarin.Essentials/Xamarin.Essentials.csproj" (default target) (1) ->
> "/Users/bradmoore/git/Essentials/Xamarin.Essentials/Xamarin.Essentials.csproj" (Build target) (1:5) ->
> (_CheckForUnsupportedTargetFramework target) -> 
>   /usr/local/share/dotnet/sdk/2.1.302/Sdks/Microsoft.NET.Sdk/targets/Microsoft.NET.TargetFrameworkInference.targets(96,5): error : The TargetFramework value 'Xamarin.WatchOS10' was not recognized. It may be misspelled. If not, then the TargetFrameworkIdentifier and/or TargetFrameworkVersion properties must be specified explicitly. [/Users/bradmoore/git/Essentials/Xamarin.Essentials/Xamarin.Essentials.csproj]

What should the is there a specific TargetFramework for WatchOS, or is there anything else I needed to also modify?

**Comment by Redth** [comment] 2018-11-02 01:03
Sorry folks, not currently on our roadmap.  Closing for now, we will definitely reconsider in the future.

**Comment by Redth** [comment] 2018-11-02 01:04
I'll add, worst case, you can do as others have done and copy/paste the relevant bits you need for your WatchOS project for now!

**Closed by Redth** 2018-11-02 01:03 UTC
Labels: not on roadmap
