### ISSUE TITLE
[Bug][Android] MediaPicker permission for storage read doesn't work as intended on Android

### ISSUE THREAD

**Issue by McFlemchSoda** [xamarin/Essentials#1656] opened 2021-01-26 13:25 UTC
I found this closed issue which exactly represents the issue with MediaPicker now: [#1537](https://github.com/xamarin/Essentials/issues/1537)

Recap and quoting the closed issue:
"When using the MediaPicker on Android (Android 8 & 10) I noticed that the permission prompt for the storage read permission didn't work properly: When choosing "Deny" from the prompt the file system is still opened, even though it shouldn't. From reading the [source code](https://github.com/xamarin/Essentials/blob/main/Xamarin.Essentials/MediaPicker/MediaPicker.android.cs) it seems that the permission is only asked, but nothing is done with the result (line 25): await Permissions.RequestAsync<Permissions.StorageRead>();."

Feels like an unfortunate copy/paste bug. 

### Steps to Reproduce
1. Bind the MediaPicker.PickPhotoAsync() method to a button.
2. Run the application on an Android device (I did this on a Samsung with Android 8 & 10).
3. Press the button that has PickPhotoAsync bound to
4. From the permission prompt select "Deny"

### Expected Behavior
Photo system doesn't open.

### Actual Behavior
Photo system opens, even though it shouldn't have the right permission. User is still able to navigate the file system and pick files from it.

### Basic Information
- Version with issue: Xamarin.Essentials 1.6.0
- Last known good version:
- IDE: VS for Mac
- Platform Target Frameworks: 
  - Android: 8 & 10
- Android Support Library Version: 
- Nuget Packages: Xamarin.Essentials 1.6.0
- Affected Devices: Sansumg Galaxy S8 Android 8 & Samsung A50 Android 10

### Workaround
I'm working around this issue by prompting the permission request myself before we use the MediaPicker. If the user denies, the user won't be able to use this functionality.

**Comment by mattleibow** [comment] 2021-01-26 17:52
This was fixed in the new 1.6.1 release.

Duplicate of #1649

**Comment by McFlemchSoda** [comment] 2021-01-26 20:30
@mattleibow When I look at that issue, and looking at the PR changes, it only changes it for FilePicker, not for MediaPicker. The same needs to be done for MediaPicker. Or am I missing something? PR files changed: https://github.com/xamarin/Essentials/pull/1651/files
Issue in MediaPicker: https://github.com/xamarin/Essentials/blob/main/Xamarin.Essentials/MediaPicker/MediaPicker.android.cs

**Comment by mattleibow** [comment] 2021-01-26 22:59
We can just pretend this did not happen...

**Closed** 2021-01-27 23:59 UTC
Labels: bug

**Comment by aodegov** [comment] 2022-02-11 15:31
As far as I can see issue still exists, once Permissions was Denied by user  
for the await MediaPicker.PickPhotoAsync(..):

![image](https://user-images.githubusercontent.com/24685526/153620213-ebb37fcb-7baf-4758-97fd-4d1e98c1dcbf.png)

**Comment by andycnguyen** [comment] 2022-10-06 17:42
I'm still finding this issue as well.
