### ISSUE TITLE
Secure storage NotSupportedException

### ISSUE THREAD

**Issue by domagojmedo** [xamarin/Essentials#430] opened 2018-07-30 08:03 UTC
### Description

On Huawei Mate 9 (maybe on others, haven't tested) calling SecureStorage.SetAsync throws System.NotSupportedException. Is this supposed to happen? I don't see it documented anywhere. If it's expected can the documentation be updated that it can throw exception?

### Steps to Reproduce

1.  Deploy app to Huawei Mate 9
2. Call SecureStorage.SetAsync

### Expected Behavior
Should save data to keystore

### Actual Behavior
Throws System.NotSupportedException exception

### Basic Information

- Platform Target Frameworks: 
  - Android: 8.1
- Android Support Library Version: v0.8.0-preview
- Affected Devices: Huawei Mate 9

### Stack trace
![stack trace](https://user-images.githubusercontent.com/12157224/43385923-5cc4a0a6-93e2-11e8-9d9c-344def31e4d0.png)
[report-2518696000496669999-5f4ce1d5-b8f7-481c-b871-9fc349a0b090.txt](https://github.com/xamarin/Essentials/files/2240247/report-2518696000496669999-5f4ce1d5-b8f7-481c-b871-9fc349a0b090.txt)

**Comment by jamesmontemagno** [comment] 2018-07-30 14:40
Duplicate of: https://github.com/xamarin/Essentials/issues/381

**Closed by jamesmontemagno** 2018-07-30 14:40 UTC
