### ISSUE TITLE
[Bug] Connectivity.ConnectivityChanged get called twice 

### ISSUE THREAD

**Issue by nkkin** [xamarin/Essentials#1068] opened 2020-01-21 19:55 UTC
### Description
 Connectivity.ConnectivityChanged get called twice at the same time if both data and wifi are enabled 
### Steps to Reproduce

1. 
2. 
3. 

### Expected Behavior
it should just run once when the connectivity or let's say internet is back not for every internet type 
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jamesmontemagno** [comment] 2020-01-28 01:58
Can you provide a sample? If you are changing networks then each time it would prompt a change.

**Comment by jamesmontemagno** [comment] 2020-02-07 21:10
This is working as intended if you change 2 different internet types. Closing up for now.

**Closed by jamesmontemagno** 2020-02-07 21:10 UTC
Labels: bug

**Comment by anotherlab** [comment] 2020-04-27 04:12
### Description
I can reproduce on Android (API 28) with Essentials 1.5.3.1 with the following conditions

### Steps to Reproduce
1. Create a new Forms App
2. Use the Shell Template and new up a Shell App
3. Add the following to AppShell(), in AppShell.xaml.cs
```
Connectivity.ConnectivityChanged += Connectivity_ConnectivityChangedAsync;
```
4. then add
```
async void Connectivity_ConnectivityChangedAsync(object sender, ConnectivityChangedEventArgs e)
{
    var access = e.NetworkAccess;
    var profiles = e.ConnectionProfiles.ToList();

    if (access == NetworkAccess.Internet)
    {
        await App.Current.MainPage.DisplayAlert("Network access", "Internet access available", "Ok");
    }
    else
    {
         await App.Current.MainPage.DisplayAlert("Network access", "Internet access unavailable", "Ok");
    }
}
```
5. Run app on Android (I used an emulator)
6. Turn on Airplane mode
Connectivity.ConnectivityChanged fires once, as expected
7. Turn off Airplane mode
 
### Expected behavior
Either Connectivity.ConnectivityChanged fires once, with ConnectionProfiles containing all of the network interfaces now working, or it fires for each network interface working.

### Actual Behavior
Connectivity.ConnectivityChanged fires twice, first time with ConnectivityChangedEventArgs.ConnectionProfiles containing Cellular
2nd time with ConnectivityChangedEventArgs.ConnectionProfiles containing Cellular and Wifi

Should you get Connectivity.ConnectivityChanged fired twice for Cellular?

### Basic Information

- Version with issue: 1.5.3.1
- Last known good version: N/A
- IDE: Visual Studio 16.5.4
- Platform Target Frameworks: 
  - Android: 9
- Android Support Library Version: N/A
- Nuget Packages:
- Affected Devices:
