### ISSUE TITLE
[Bug]  iOS device with MediaPicker does not consider the device orientation

### ISSUE THREAD

**Issue by WaldemarCichon** [xamarin/Essentials#1965] opened 2022-02-10 00:00 UTC
### Description

Pictures made with an iOS device with MediaPicker does not consider the device orientation

### Steps to Reproduce

1.  Compile a simple app making photos
2.  Make photo with an iOS.Device
3.  Change device orientation; made subsequent photo

### Expected Behavior
Each photo has the correct orientation and also portrait-photos appear as portrait.

### Actual Behavior
Photos appear all in landscape and sometimes also bottom up
### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages: 17.0; 17.1
- Affected Devices:
all iOS-Devices

**Comment by jfversluis** [comment] 2022-04-05 20:08
Duplicate of #1514

**Closed by jfversluis** 2022-04-05 20:08 UTC
Labels: bug
