### ISSUE TITLE
[Enhancement] Add text to FileShare

### ISSUE THREAD

**Issue by IgorKravchenko10** [xamarin/Essentials#952] opened 2019-10-25 18:48 UTC
## Summary
We have an ability to share files - it is great! But often we need to send simple text with file. My propose is to add string property to ShareFileRequest class. In Android implementation will be enough to add intent.PutExtra(Intent.ExtraText, request.message);

## API Changes
In ShareFileRequest add property:

```
public class ShareFileRequest 
{
...
public string Text { get; set; }
}
```

In Android implementation in method PlatformRequestAsync(ShareFileRequest request) just add:
`intent.PutExtra(Intent.ExtraText, request.message);`

I don't know how to implement it in iOS but I think there is same behavior.

So API will be:
```
await Share.RequestAsync(new ShareFileRequest
{
    Title = Title,
    File = new ShareFile(file),
    Text = text
});
```

**Comment by tekmun** [comment] 2019-11-20 14:36
I would like to have this feature too for all platforms.  Thanks.

**Comment by jjchiw** [comment] 2020-04-07 21:31
Hi

I need this too, but it seems odd, I started to add the features in Android and IOS and it seems it works, but not all the apps accepts text and attachment

I  tested with OneNote, Gmail, WhatsApp y Slack

Slack
- With text and attachment
  - Only pastes text

WhatsApp
- With text and attachment
   - Only pastes the attachment

Gmail and OneNote works as expected by me :)

https://github.com/jjchiw/Essentials/commit/0acc0c1e97bf1ec9f37dc6d4c6bbe90b6cff57df

Autoformat makes a lot of changes :/

**Comment by AlexanderMelchers** [comment] 2020-06-29 07:26
This seems a duplicate of #858.

**Comment by mattleibow** [comment] 2020-11-06 02:00
Duplicate of https://github.com/xamarin/Essentials/issues/858

**Closed by mattleibow** 2020-11-06 02:00 UTC
Labels: feature-request, up-for-grabs
