### ISSUE TITLE
Connectivity - Add Wi-Fi signal strength

### ISSUE THREAD

**Issue by YZahringer** [xamarin/Essentials#480] opened 2018-08-19 15:09 UTC
## Description of Feature
Get the signal strenght for connected Wi-Fi network. 

### Specific platform APIs
- [iOS](https://developer.apple.com/documentation/networkextension/nehotspotnetwork/1618923-signalstrength)
- [Android](https://developer.android.com/reference/android/net/wifi/WifiManager#calculateSignalLevel(int,%20int))
- [UWP](https://docs.microsoft.com/en-us/uwp/api/windows.devices.wifi.wifiavailablenetwork.signalbars#Windows_Devices_WiFi_WiFiAvailableNetwork_SignalBars)

> VS bug [#733079](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/733079)

**Comment by Redth** [comment] 2018-11-02 00:43
Someone needs to figure out how we normalize this and provide an API spec for it.

Given that UWP returns Signal Bars we probably need to be pretty simple in our API.  I'm guessing this is some value between like 1-5 only, which is probably good enough for what most people would _use_ this API for (to detect a weak or really good signal).  The UWP docs don't really say what the expected value ranges are for this so we need to figure that out.

If someone wants to draft a spec and figure out how we normalize this across the platforms we can continue the discussion!

**Comment by Mrnikbobjeff** [comment] 2018-11-08 15:54
Normalisation is quite forard. Android offers inbuild normalization which "should be used any time signal strength is shown." iOS offers a range between 0 and 1, which is also super easy to adapt to whatever degree of detail we choose. The UWP doc is pretty unspecific, I only managed to reproduce values between one and three. I'd thus suggest to implement this via

public enum SignalStrength
{
  Unknown,
  Weak,
  Fair,
  Strong
}

where we simply use the UWP values as provided (1-3 bars), on android we use
public static int calculateSignalLevel (int rssi, Int numLevels)
which "Calculates the level of the signal. This should be used any time a signal is being shown."
on iOS we divide the possible range by 3 and have the corresponding enum value.
If this would be accebtable I would be willing to implement this and have it assigned to me.

**Comment by pictos** [comment] 2018-11-08 16:32
@Redth  , this API can be very simple ... We can expose an int property for the force signal, in the range 0 to 5. 

```csharp
 public static int SignalStrenght => PlataformSignal();
```

### Android
Need permission of ACCESS_WIFI_STATE

### iOS
I did the implementation, but I don't have a MAC so if any one can test I will be grateful.

### UWP
I test in PC, and don't need extra configuration.


You can see the full implementation [here](https://github.com/pictos/Specs/tree/master/Plataforms/Signal), I did it in the same way as Xamarin Essentials.

**Comment by Redth** [comment] 2018-11-08 18:58
I think I'd like to see this spec done as an enum of SignalStrength types (Unknown, None, Weak, Fair, Strong) rather than a numerical value.  I think the main motivation to use this API would be to do some sort of logic or visual messaging to the user when the signal is Weak or None, so we should help decide when that is for the user and not make them determine what number value to pivot on.

**Comment by pictos** [comment] 2018-11-08 22:15
I understood what you mean, I thought of putting value as number for analytical purposes, like displaying it on a graph or something ... I'll change the spec to an enum and put it here for you to look at.

**Comment by pictos** [comment] 2018-11-09 12:45
@Redth  done. Now the propertie return the enum. Like this:

```csharp
 public static SignalStrength SignalStrenght => PlataformSignal();
```
And enum:
```csharp
public enum SignalStrength
{
    Unknown = 0,
    None = 1,
    Weak = 2,
    Fair = 3,
    Strong = 4
}
```
I noticed a peculiarity in UWP, when the device is disconnected from the network (wifi) or in airplane mode the value returned is null. And as a treatment, whenever the value is null it returns `Unknow`. 

So, if the user is offline and the wifi is on, the return should be `None`, can this be a problem?
If it's a problem, one solution I thought we'd check is if the wifi sensor is turned on. If it's turned on we return `None`, otherwise we return `Unknow`.

**Comment by jamesmontemagno** [comment] 2018-11-10 01:10
Code looks pretty good. If you a PR I can make comments on the code.

I think that since this is only WiFi it should be:

```csharp
public SignalStrength WiFiSignalStrength { get; }
```

This would clearly define what it means.

**Comment by pictos** [comment] 2018-11-10 15:10
@jamesmontemagno  , @Redth  . The PR is to master branch or dev/api-fix?

**Comment by Mrnikbobjeff** [comment] 2018-11-10 15:18
https://github.com/xamarin/Essentials/pull/616

**Comment by jamesmontemagno** [comment] 2019-06-17 18:14
If you look at #647 and research has determined that it isn't doable on iOS and wont be added into the API in the future as it is not reliable.

**Closed by jamesmontemagno** 2019-06-17 18:14 UTC
Labels: feature-request, in progress
