### ISSUE TITLE
[Bug] Android 11 FileProvider runtime error

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Essentials#1391] opened 2020-09-22 10:50 UTC
### Description

System.TypeLoadException: 'Could not load type 'Xamarin.Essentials.FileProvider' from assembly 'Xamarin.Essentials, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.'

### Steps to Reproduce

1. Create default XF Shell app
2. Modify Target Framework to 11.0 and run application using Android R emulator
3. 

### Expected Behavior
No crash 
### Actual Behavior
System.TypeLoadException: 'Could not load type 'Xamarin.Essentials.FileProvider' from assembly 'Xamarin.Essentials, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'.'
### Basic Information

- Version with issue: 1.5.3.2 and later
- IDE: Visual Studio 16.8.0 Preview 3
- Platform Target Frameworks: 
  - iOS:  not verified
  - Android: Android R
- Android Support Library Version: 
- Nuget Packages: 
```
<PackageReference Include="Plugin.CurrentActivity" Version="2.1.0.4" />
    <PackageReference Include="Microsoft.AppCenter.Analytics" Version="3.4.1" />
    <PackageReference Include="Microsoft.AppCenter.Crashes" Version="3.4.1" />
    <PackageReference Include="Xamarin.Forms" Version="4.8.0.1451" />
    <PackageReference Include="Xamarin.Essentials" Version="1.5.3.2" />
```
- Affected Devices:

### Screenshots

![image](https://user-images.githubusercontent.com/33021114/93873584-a1739c80-fcda-11ea-8a5d-d9b6c6c141b2.png)

**Comment by domyd** [comment] 2020-10-02 12:05
Running into this as well. Is there a workaround? This means that any app that uses Xamarin.Essentials doesn't work on Android 11, no?

**Comment by jamesmontemagno** [comment] 2020-10-02 23:22
Your Compile and Target should always match. This is best practicej.

Are you using an API at all?

Following your steps it worked for me.

![image](https://user-images.githubusercontent.com/1676321/94976949-7ef83500-04cb-11eb-8d76-413c4e7a7a2b.png)

**Comment by jamesmontemagno** [comment] 2020-10-02 23:23
My Project
[App22.zip](https://github.com/xamarin/Essentials/files/5320724/App22.zip)

**Comment by VladislavAntonyuk** [comment] 2020-10-05 19:28
[MOVEitMobile.zip](https://github.com/xamarin/Essentials/files/5329660/MOVEitMobile.zip)

**Comment by VladislavAntonyuk** [comment] 2020-10-15 16:15
@jamesmontemagno I found that by adding this to csproj fixes the issue:
```
<AotAssemblies>false</AotAssemblies>
    <EnableLLVM>false</EnableLLVM>
    <AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>
    <BundleAssemblies>false</BundleAssemblies>
    <EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
```

**Comment by VladislavAntonyuk** [comment] 2020-10-15 20:34
It is the only difference between template project and the one you attached

**Comment by mattleibow** [comment] 2020-10-26 14:55
I had a chat with the Android team and the issue is that Android 11 decided not to work as it always has. As a result, the fastdev support is broken, right now, but is actually fixed again in an upcoming preview of VS 16.9 Preview 1. I am not sure of the timeline for that exactly, but for now you can disable the fastdev by adding `<EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>` or unchecking the "Use Fast Deployment" box in VS:

![image](https://user-images.githubusercontent.com/1096616/97188313-0b84d300-17ac-11eb-9ded-3cbdc5e86832.png)

**Comment by mattleibow** [comment] 2020-10-26 14:57
I'm closing this for now as we have to wait for the VS update. And I believe the new VS also has a much better fast dev, so all good things coming soon.

**Closed by mattleibow** 2020-10-26 14:57 UTC
Labels: bug

**Comment by VladislavAntonyuk** [comment] 2020-10-26 15:07
@mattleibow when it is fixed, can I remove `<EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>`?

**Comment by mattleibow** [comment] 2020-10-26 15:15
Yes. That is basically disabling fastdev. Very confusing name, but that is marketing vs engineering for you :) @dellis1972 Is the new fastdev going to be using the same element name in the csproj, or is this something fancy and new?

**Comment by dellis1972** [comment] 2020-10-26 16:46
@mattleibow  to keep things simple we are using the same element name `EmbedAssembliesIntoApk` .
