### ISSUE TITLE
Android OrientationSensor Monitoring Freezes App

### ISSUE THREAD

**Issue by adamzucchi** [xamarin/Essentials#797] opened 2019-05-23 19:36 UTC
### Description
Monitoring Xamarin.Essentials OrientationSensor changes leads to complete device lock-up/freeze on Android.

### Steps to Reproduce

1. Create new Xamarin.Forms solution/project (make sure an Android project is created).
2. Ensure you have the Xamarin.Essentials Nuget package installed (1.1.0 currently comes down by default with a new Xamarin.Forms project).
3. In App.xaml.cs constructor start monitoring for the "ReadingChanged" event from the OrientationSensor in Xamarin.Essentials.
4. Build and deploy to physical device (I'm deploying a debug build to a Google Pixel 3) that is laying on a desk with the app in portrait orientation and once the app is deployed to the Pixel 3 the device is not interacted with by a user (just watch for app output).
5. Monitor the Application Output for the following type of output:

[ationsensortes] Explicit concurrent copying GC freed 34243(1446KB) AllocSpace objects, 0(0B) LOS objects, 50% free, 1482KB/2MB, paused 20us total 5.930ms
[Mono] GC_TAR_BRIDGE bridges 3269 objects 3275 opaque 2 colors 3269 colors-bridged 3269 colors-visible 3269 xref 0 cache-hit 0 cache-semihit 0 cache-miss 0 setup 0.10ms tarjan 0.66ms scc-setup 0.33ms gather-xref 0.03ms xref-setup 0.01ms cleanup 0.43ms
[Mono] GC_BRIDGE: Complete, was running for 18.83ms
[Mono] GC_MINOR: (Nursery full) time 11.05ms, stw 12.20ms promoted 710K major size: 1488K in use: 857K los size: 1024K in use: 76K

6. That output begins to occur more frequently the longer the application is open and running.

7. Just after ~15 minute mark of the app running untouched on the Pixel 3 the UI becomes unresponsive and the OS prompts the user to decide to close the app or wait and the application output window is flooded with the above garbage collection output.  The ~15 minutes may be different based on the device you are deploying to. (this is not an issue on iOS)

### Expected Behavior
The application would remain responsive and not freeze up when monitoring for orientation changes.

### Actual Behavior
The application becomes unresponsive after ~15 mins of time when the OrientationSensor is subscribed to ReadingChanged events.

### Basic Information

- Version with issue: Xamarin.Forms 4.0 and Xamarin.Essentials 1.1.0 (previous versions also have the above issue)
- Last known good version: Unknown (or none)
- IDE: Visual Studio for Mac
- Platform Target Frameworks:
  - Android: 8.1
- Android Support Library Version: 28.0.0.1
- Nuget Packages: Xamarin.Essentials 1.1.0
- Affected Devices: Android Google Pixel 3 (probably other Android models as well)

### Reproduction Link
[Reproducible Sample Project](https://github.com/adamzucchi/XFOrientationSensorTest)

**Comment by jamesmontemagno** [comment] 2019-05-23 20:18
Can you upload a sample on a git repo for us, i don't like to download zip directories.

**Comment by adamzucchi** [comment] 2019-05-23 20:31
@jamesmontemagno - Absolutely, and done! (I'll keep that in mind for future as well)

Public Github Repository: [https://github.com/adamzucchi/XFOrientationSensorTest](https://github.com/adamzucchi/XFOrientationSensorTest)
 
One more note to make on the above, it appears that the **SensorSpeed.UI** (which must be a more frequent/fast reading of the orientation) is where the issue is more likely to occur and occur faster.  When SensorSpeed.UI is used the freeze happens in ~15 minutes (as reported above in my initial report), however I am currently running another test with **SensorSpeed.Default** and that instance of the app is still running fine after ~30 minutes of use.

**Comment by adamzucchi** [comment] 2019-05-23 20:36
@jamesmontemagno  - The app did end up freezing with the use of SensorSpeed.Default after ~38 mins or so.

**Comment by jamesmontemagno** [comment] 2019-05-24 03:45
One other question for you... are you rotating the device or just letting it sit there?

**Comment by adamzucchi** [comment] 2019-05-24 12:12
@jamesmontemagno - My test was done with the device laying flat on a desk top (with the Pixel 3 displaying in portrait) and left untouched during the test.  

My guess is however that it would not matter if you did change orientations during the test.

**Comment by jamesmontemagno** [comment] 2019-05-24 18:40
So... one thing to note here is that the "[OrientationSensor](https://docs.microsoft.com/xamarin/essentials/orientation-sensor?context=xamarin/xamarin-forms&amp;WT.mc_id=docs-github-jamont)" is the sensor for the device, not the device orientation... 

You will want to use the [Device Display API](https://docs.microsoft.com/xamarin/essentials/device-display?context=xamarin%2Fxamarin-forms&amp;tabs=android&amp;WT.mc_id=docs-github-jamont)

This is the code you would want:

```csharp
public class DisplayInfoTest
{
    public DisplayInfoTest()
    {
        // Subscribe to changes of screen metrics
        DeviceDisplay.MainDisplayInfoChanged += OnMainDisplayInfoChanged;
    }

    void OnMainDisplayInfoChanged(object sender, DisplayInfoChangedEventArgs  e)
    {
        // Process changes
        var displayInfo = e.DisplayInfo;
    }
}
```

**Comment by jamesmontemagno** [comment] 2019-05-30 00:28
Closing here as I am unable to reproduce the core bug and provided updated correct code.

**Closed by jamesmontemagno** 2019-05-30 00:28 UTC
