### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by WaldemarCichon** [xamarin/Essentials#1945] opened 2021-12-29 23:52 UTC
### Description

CapturePictureAsync does not consider the orientation of the camera. It always makes photos in portrait mode. The photo shown before to chose or retake the photo has a correct orientation.

I think this is because the OrientationSensor does not work correctly under IOS

### Steps to Reproduce

1. Use MediaPicker.CapturePhoto to make a photography in landscape
2. Confirm the photo (photo is in correct orrientation
3. find the photo in portrait mode

### Expected Behavior
Photo is in landscape
### Actual Behavior
Photo in in portrait orientation
### Basic Information

- Version with issue: 1.7.0
- Last known good version:
- IDE: Visual Studio Mac, newest
- Platform Target Frameworks: 
  - iOS:  15.4.00 
  - Android: 12.0.0.3  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices: iPad / iPhone

**Comment by jfversluis** [comment] 2022-01-03 19:45
Duplicate of #1514

**Closed by jfversluis** 2022-01-03 19:45 UTC
Labels: bug
