### ISSUE TITLE
Launcher Openasync not working for filesystem in ios.

### ISSUE THREAD

**Issue by arjun159** [xamarin/Essentials#907] opened 2019-09-18 10:23 UTC
Issue while trying to open a pdf file from filesystem in ios,it's working fine in android.

var filePath = Path.Combine(FileSystem.AppDataDirectory, fileName);
 byte[] bytes = response.Content.ReadAsByteArrayAsync().Result;
 File.WriteAllBytes(filePath, bytes);
 await Launcher.OpenAsync(new OpenFileRequest { File = new ReadOnlyFile(filePath) });

- Version with issue:1.3.0
- Platform Target Frameworks: 
  - iOS:  12.0

**Comment by jamesmontemagno** [comment] 2019-09-18 17:18
Can you upload a small repro of your project to help us triage please.

What happens when it is called? Does anything pop up? it could be that it is not supported on the system perhaps or an app can't read it.

**Comment by KijongHan** [comment] 2019-10-17 00:20
I seem to be having this issue as well on Xamarin.Essentials 1.3.1 / iOS 12.4. A popup with apps that can open the pdf shows up, but selecting an app does nothing.

No issues on Android

**Comment by JunkyXL86** [comment] 2019-11-06 14:15
> I seem to be having this issue as well on Xamarin.Essentials 1.3.1 / iOS 12.4. A popup with apps that can open the pdf shows up, but selecting an app does nothing.
> 
> No issues on Android

Same here. Android works. iOS see attached screenshot:
![grafik](https://user-images.githubusercontent.com/3984217/68305564-2d231100-00a8-11ea-90d8-386e87b3d0b0.png)

**Comment by SuNNjek** [comment] 2019-12-19 10:56
I think I have the same error. When I select "Save to Files" in my app, a small popup flashes on the screen and I get the following error in the debug output:
```
[ShareSheet] cancelled request - error: The operation couldn’t be completed. Invalid argument
```

I managed to reproduce the bug in a test project: 
[Essentials907.zip](https://github.com/xamarin/Essentials/files/3983183/Essentials907.zip)

**Comment by jamesmontemagno** [comment] 2019-12-19 16:01
Have you run it on a physical device?

**Comment by SuNNjek** [comment] 2019-12-19 16:13
Not the test app. But I know the error also happens on physical devices

**Comment by jamesmontemagno** [comment] 2019-12-19 16:18
I'll give it a look thanks!

**Comment by EvoPulseGaming** [comment] 2019-12-25 16:16
running the same code, on UWP does nothing.... not even a pop up

**Comment by RhomGit** [comment] 2019-12-29 08:21
I am on a physical iPad (iOS 13) and am experiencing all of the above also.
I had the same result as @SuNNjek with a bit more diagnostic below:.

- Could not instantiate class NSURL. Error: Error Domain=NSCocoaErrorDomain Code=4864 "The URL archive of type “public.url” contains invalid data." UserInfo={NSDebugDescription=The URL archive of type “public.url” contains invalid data.}

- Could not instantiate class NSURL. Error: Error Domain=NSCocoaErrorDomain Code=4864 "The URL archive of type “public.url” contains invalid data." UserInfo={NSDebugDescription=The URL archive of type “public.url” contains invalid data.}

- Can't end BackgroundTask: no background task exists with identifier 14 (0xe), or it may have already been ended. Break in UIApplicationEndBackgroundTaskError() to debug.

**Comment by jamesmontemagno** [comment] 2020-01-03 19:27
@SuNNjek i ran your sample on iOS 13.3 on my iPhone 8 and it worked flawless. It opened up the the share sheet and i selected save to files, created a new file and boom it worked. I opened the file up from the files app.

**Comment by jamesmontemagno** [comment] 2020-01-03 19:31
I also tested our sample app on iOS 13.3 (iPhone 8) and save a file as a pdf and opened it in notes with both the share api and launcher API without issue.

I will test on my older iPhone 6, which is locked to ios 12

**Comment by jamesmontemagno** [comment] 2020-01-03 19:44
@SuNNjek I just tested your sample on iOS 12 and did save to file and it worked just fine there too

**Comment by SuNNjek** [comment] 2020-01-03 19:54
@jamesmontemagno Ok, I'll try updating all my packages and see if the issue persists on Monday (don't actually own any Apple stuff personally, so I can only test at work)

**Comment by jamesmontemagno** [comment] 2020-01-03 19:55
@EvoPulseGaming TryOpenAsync is not for files, only for Uris. That is why it is returning false.

**Comment by jamesmontemagno** [comment] 2020-01-03 19:59
Gotcha, i spent 1 hour testing all different apps file types on both iOS 13 + iOS 12 and no issues. Closing as can not reproduce here on any of the reports here.

**Closed by jamesmontemagno** 2020-01-03 19:59 UTC
Labels: bug

**Comment by RhomGit** [comment] 2020-01-04 06:09
@SuNNjek @jamesmontemagno 
I ran the sample from @SuNNjek sample on a physical iOS 13 iPad. I initially was able to replicate the issue using his app but it then stopped occurring. The same goes for our production release. It occurred and now it doesn't. Uninstalled the apps/restarted the device …. it just all seems to work correctly now.

Note: the errors in my message above only output when the issue is observed.
