### ISSUE TITLE
GeoLocation: Add Event for Location Changed

### ISSUE THREAD

**Issue by gceaser** [xamarin/Essentials#717] opened 2019-02-24 22:51 UTC
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by jamesmontemagno** [comment] 2019-02-27 04:19
Duplicate of https://github.com/xamarin/Essentials/issues/290

**Closed by jamesmontemagno** 2019-02-27 04:19 UTC
