### ISSUE TITLE
[Bug] Mail Send button is disable

### ISSUE THREAD

**Issue by LeeMaZong** [xamarin/Essentials#1462] opened 2020-10-22 09:32 UTC
### Description
Hello,
I use xamarin essential to send email, everything works fine on all systems (iOS/Android) except for an iOS device where I removed the Apple native Mail app and installed GMail (So GMail is my default e-mail app).
When I try to send an e-mail with Xamarin Essential, it opens GMail fine but I am unable to send the mail. The send button is disabled.

My code to send E-Mail:
```
var message = new EmailMessage
{
    Subject = "my subject",
    Body = "<div>some html text</div>",
    To = new List<string>() {"myemail@host.com"},
    BodyFormat = EmailBodyFormat.Html
};
await Email.ComposeAsunc(message);
```

### Steps to Reproduce

1. open email with await Email.ComposeAsunc(message);

### Expected Behavior
the email window with the send button enable.

### Actual Behavior
the email window with the send button disable.

### Basic Information

- Version with issue: 1.4.0
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:   10.0
- Nuget Packages: Xamarin.essential 1.4.0
- Affected Devices: Apple devices

**Comment by jamesmontemagno** [comment] 2020-10-22 20:42
Duplicate of: https://github.com/xamarin/Essentials/issues/1401

**Closed by jamesmontemagno** 2020-10-22 20:42 UTC
Labels: bug

**Comment by LeeMaZong** [comment] 2020-10-23 08:07
Hello James,
not really beacause I have the same issue in iOS 12 and 13 and I don't have Apple Mail App anymore. 
So it is the right default app (GMail) that opens.
It launches the GMail form to write the email, but only the send button is grayed out.
The behavior of this issue is not the same but the origin may be the same...

So do you think that by solving the #1401, that should solve this one ?
Thanks.
