### ISSUE TITLE
File picker for Xamarin Forms

### ISSUE THREAD

**Issue by StanleyBroo** [xamarin/Essentials#918] opened 2019-10-07 15:43 UTC
### Description
Missing feature: File picker for Xamarin Forms, a must have for any LOB app. Can't see why this isn't under the Essentials umbrella allready.
I.e upload a pdf from disk ...filepicker?

**Comment by jamesmontemagno** [comment] 2019-10-12 18:32
Duplicate of: https://github.com/xamarin/Essentials/issues/251

**Closed by jamesmontemagno** 2019-10-12 18:32 UTC
