### ISSUE TITLE
Errors in production for authentication (Android)

### ISSUE THREAD

**Issue by maxal1917** [xamarin/Essentials#1667] opened 2021-01-31 23:07 UTC
### Description
After upgrading to 1.6.0, there are errors in logs related to authentication.

### Steps to Reproduce
I could not reproduce it locally, but I had 57 errors from 8 users in the last 3 days, after pushing newest version. The errors were reported as crashes in AppCenter.

[report-2517901836257609999-5187f991-ffde-474c-868b-573df03b584f.txt](https://github.com/xamarin/Essentials/files/5900973/report-2517901836257609999-5187f991-ffde-474c-868b-573df03b584f.txt)

### Expected Behavior
There should be no crashes for app.

### Actual Behavior
Crashes are reported in App Center.

### Basic Information

- Version with issue:
- Last known good version: 1.5.3.2
- IDE:
- Platform Target Frameworks: 
  - Android: 1.6.0
- Nuget Packages: Xamarin.Essentials
- Affected Devices: Multiple devices.

**Comment by mattleibow** [comment] 2021-02-01 03:36
Closing this as a duplicate of #1586 and a duplicate of #1626

Please see there for more info.

**Closed by mattleibow** 2021-02-01 03:36 UTC
Labels: bug
