### ISSUE TITLE
[Bug] DisplayInfoChanged invoked with wrong orientation

### ISSUE THREAD

**Issue by BaseCrusher** [xamarin/Essentials#1355] opened 2020-08-20 08:10 UTC
### Description
When observing the MainDisplayInfoChanged of DeviceInfo you get Orientation Landscape when entering Protrait and vice versa.
In Addition to this, the OnDeviceOrientationChanged Event is only fired after you roatated the screen a second time.

On iOS it works as it should.

### Steps to Reproduce

1.  Create a new Forms Project.
2.  Observe the OnDeviceOrientationChanged and write out the args.DisplayInfo.Orientation.
3.  Start the application and rotate the phone.

### Expected Behavior

MainDisplayInfoChanged should be invoke on the first roatation not only after the second.
When the phone is roatated to Landscape the Orientation in the DisplayInfoChangedEventArgs should be Landscape as well.
Same goes for Portrait.

### Actual Behavior

MainDisplayInfoChanged invokes only after the second roatation.
When the phone is roatated to Landscape the Orientation in the DisplayInfoChangedEventArgs is Portrait. The same issue applies to Portait rotation.

### Basic Information

- Version with issue: 1.5.3.2
- Last known good version: -- 
- IDE: Visual Studio 2019 (version 16.7.2)
- Platform Target Frameworks: 
  - iOS:  --
  - Android: 9.0
  - UWP:  --
- Nuget Packages: --
- Affected Devices: All Andorid Phones

### Reproduction Link

[Link](https://drive.google.com/file/d/1IaoCeaCgOm25zcjdunQScCyUN2CtY8zW/view?usp=sharing)

**Comment by StargazerNC** [comment] 2020-11-05 18:38
I can confirm this one too. Same steps to reproduce.

**Comment by EvanMulawski** [comment] 2020-12-01 20:20
Can also confirm this issue. Any update on when this will be fixed?

**Comment by mattleibow** [comment] 2020-12-02 03:18
I can't seem to reproduce this. Just tested the sample app on my Android 9 device.

Could you submit a sample app or a snippet that I can copy paste and see what the difference is?

**Comment by IndianaGary** [comment] 2020-12-03 00:42
Mattleibow: The issue is not with a physical device, just the Android emulator.

**Comment by jamesmontemagno** [comment] 2020-12-03 01:19
I think it is a known issue maybe on emulators something with timing.

**Comment by mattleibow** [comment] 2020-12-03 01:50
Ah.... Maybe in the event handler, you can add a delay before actually reading the values? Probably just needs like a 10ms delay or even less.

**Comment by BaseCrusher** [comment] 2020-12-16 17:13
@mattleibow 
Sorry for the late response, I was preatty busy the last cuple weeks.

So I've updated the sample project and tested it out.
It is true, when running the code on a phisical device this works just fine, but even after adding a delay to the event call I still get the same wrong behaviour on the simulator. Orientation and first event call are messed up as explained in the initial thread. I have added it as followed:

```
        public App()
        {
            InitializeComponent();

            MainPage = new MainPage();

            DeviceDisplay.MainDisplayInfoChanged += async (s, a) => { await OnDeviceOrientationChanged(s, a); };
        }

        async Task OnDeviceOrientationChanged(object Sender, DisplayInfoChangedEventArgs args)
        {
            await Task.Delay(10);

            if (args.DisplayInfo.Orientation == DisplayOrientation.Landscape)
            {
                Debug.WriteLine("Landscape");
            }
            else if (args.DisplayInfo.Orientation == DisplayOrientation.Portrait)
            {
                Debug.WriteLine("Portrait");
            }
        }
```

Interestingly enough I also realised that the event is called twice when using physical device. Once with the orientation that you had before turning your phone and the second one with the new orientation. This could be preatty troublesome if someone has a big chunk of code depending on the orientation.

As for the event not being raised on the first orientation switch:
On the phisical device this works without any proplems and there is only one event raised. The follow orientation changes are raising the event twice as explained in the upper section.

I haven't taken a look to how the implementation is done under the hood, but there seems to be some issues that needed to be solved.

**Comment by jamesmontemagno** [comment] 2021-04-13 20:18
I believe this is just a bug with emulators in general and no real way to get around it :(

You could put in a bigger delay and then check DeviceDisplay.MainDisplay and go from there.

A work around that I can put in the code to do this is:

```
public override async void OnOrientationChanged(int orientation)
        {
            await Task.Delay(1000);
            onChanged();
        }
```

This is probably fine and gives the device time to process the change.

**Comment by PhilippElhaus** [comment] 2021-05-01 15:35
I can confirm this bug exists on Android as described. Just wanted to report it myself.

**Comment by yshteinm** [comment] 2021-08-04 18:12
I have a problem on physical device HXY A9 Android 11.0 API 30. When I read DeviceDisplay.MainDisplayInfo.Orientation always returns DisplayOrientation.Portrait.

**Closed** 2022-01-18 12:52 UTC
Labels: bug
