### ISSUE TITLE
NFC Access

### ISSUE THREAD

**Issue by bleepzter** [xamarin/Essentials#902] opened 2019-09-10 17:25 UTC
Create an object that can hook into the NFC message loop and provide event handlers from the NFC hardware events (such as scanning nfc/rfid enabled chips).

**Comment by pw3107** [comment] 2019-09-10 18:38
Yes please.

**Comment by jamesmontemagno** [comment] 2019-09-10 20:07
Duplicate of: https://github.com/xamarin/Essentials/issues/120 as we have decided not to implement this feature into Essentials.

**Closed by jamesmontemagno** 2019-09-10 20:07 UTC
Labels: feature-request
