### ISSUE TITLE
Location is not showing data on emulator nor device

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#769] opened 2019-04-24 15:02 UTC
Hi,

I have below code and I am trying to get the location data, country, city, etc..

The latitude and longitude are correct and I tried to pass different values for different countries but getting the same.

**here is my code:**

```
var location_data = await GetLocation();

await DisplayAlert("latitude", Convert.ToString(location_data.latitude), "OK");
await DisplayAlert("longitude", Convert.ToString(location_data.longitude), "OK");

await DisplayAlert("feature_name", location_data.feature_name, "OK");
await DisplayAlert("admin_area", location_data.admin_area, "OK");
await DisplayAlert("locality", location_data.locality, "OK");
await DisplayAlert("thoroughfare", location_data.thoroughfare, "OK");

```

```
public async Task<Location> GetLocation()
{
    var UserLocation = new Location();

    try
    {
        var last_known_location = await Geolocation.GetLastKnownLocationAsync();

        if (last_known_location != null)
        {
            UserLocation.latitude = last_known_location.Latitude;
            UserLocation.longitude = last_known_location.Longitude;
        }
        else
        {
            var request = new GeolocationRequest(GeolocationAccuracy.Default);
            var location = await Geolocation.GetLocationAsync(request);

            if (location != null)
            {
                UserLocation.latitude = location.Latitude;
                UserLocation.longitude = location.Longitude;

                var placemarks = await Geocoding.GetPlacemarksAsync(UserLocation.latitude, UserLocation.longitude);

                var placemark = placemarks?.FirstOrDefault();

                if (placemark != null)
                {
                    UserLocation.admin_area = placemark.AdminArea;
                    UserLocation.country_code = placemark.CountryCode;
                    UserLocation.country_name = placemark.CountryName;
                    UserLocation.feature_name = placemark.FeatureName;
                    UserLocation.locality = placemark.Locality;
                    UserLocation.postal_code = placemark.PostalCode;
                    UserLocation.sub_admin_area = placemark.SubAdminArea;
                    UserLocation.sub_locality = placemark.SubLocality;
                    UserLocation.sub_thoroughfare = placemark.SubThoroughfare;
                    UserLocation.thoroughfare = placemark.Thoroughfare;
                }
            }
        }
    }
    catch (Exception ex)
    {
        Crashes.TrackError(ex, new Dictionary<string, string>
        {
            { "Page", "Settings" },
            { "Where", "GetLocation" }
        });
    }

    return UserLocation;
}

```

**Comment by jamesmontemagno** [comment] 2019-04-25 01:57
What are you getting?

**Comment by jrahma** [comment] 2019-04-25 08:04
Just blank values

**Comment by jamesmontemagno** [comment] 2019-05-30 23:06
I just tested this code on my Pixel 2 XL and it worked great for me. It could be that that device doesn't have a geo-coder. You will need to grab the logs for me to triage.

**Comment by jamesmontemagno** [comment] 2019-12-20 00:09
Closing as I am unable to reproduce

**Closed by jamesmontemagno** 2019-12-20 00:09 UTC
Labels: need-more-information, unable-to-reproduce
