### ISSUE TITLE
[Bug] Pick photo save the image in a wrong orientation

### ISSUE THREAD

**Issue by matteomonizza** [xamarin/Essentials#1556] opened 2020-12-01 12:39 UTC
### Description
Pick Photo saves image in a wrong orientation

### Steps to Reproduce

1. call CapturePhotoAsync
2. open the saved file with an image viewer like a web view

### Expected Behavior
the image must be in the correct orientation (up)

### Actual Behavior
the image is rotated 90°

### Basic Information

- Version with issue: 1.6
- Last known good version:
- IDE: VS 2019 mac
- Platform Target Frameworks: 
  - iOS:  14.2
- Affected Devices:
iPhone

### Screenshots
![image](https://user-images.githubusercontent.com/3415640/100741115-0124ad00-33da-11eb-84ca-4ab168b342cd.png)

![image](https://user-images.githubusercontent.com/3415640/100741178-1d284e80-33da-11eb-9fc0-df3287e55d39.png)

I think it is necessary to normalize the captured image like:

using var PickedImage = new UIImage(ImageFile);

                        if (PickedImage.Orientation != UIImageOrientation.Up)
                        {
                            UIGraphics.BeginImageContextWithOptions(PickedImage.Size, false, PickedImage.CurrentScale);

                            CoreGraphics.CGRect rect = new CoreGraphics.CGRect(0, 0, PickedImage.Size.Width, PickedImage.Size.Height);

                            PickedImage.Draw(rect);

                            UIImage ImageOK = UIGraphics.GetImageFromCurrentImageContext();

                            UIGraphics.EndImageContext();

PickedImage.AsPNG().Save(ImageFile, Foundation.NSDataWritingOptions.Atomic, out Foundation.NSError Error);

**Comment by BjornVanslembrouck** [comment] 2020-12-02 10:56
@matteomonizza, I already created a PR that fixes this: https://github.com/xamarin/Essentials/pull/1520

It has been confirmed that this fixes the rotation issue, but the comments on the PR sparked a bigger conversation. I suggested merging that in and continuing the conversation elsewhere. However the PR is still pending at the moment.

**Comment by r-work** [comment] 2020-12-02 16:58
Can confirm this happens on Android as well.
Just tried on Android 10 and image has wrong orientation.

**Comment by BjornVanslembrouck** [comment] 2020-12-02 17:06
@r-work, that PR does not fix the Android issue. Might need a separate ticket as this ticket (and the one the PR is linked to) are mentioning iOS only.

**Comment by r-work** [comment] 2020-12-02 17:17
@BjornVanslembrouck, thanks, just created #1562 for Android.

**Comment by groege** [comment] 2021-01-27 07:13
As described in #1640: RotateImage flag should be implemented.
As far as I understand the problem ist, that the image is stored ignoring the phones rotation and only the exif data in the picture contains the necessary rotation...
Therefore we need the option RotateImage which should rotate the image according to the exif data and remove the rotation data from exif.
Also it should be possible to retain Exif data as already requested in multiple duplicate issues (see #1640 for an overview)
same here: #1641 1562

**Comment by jfversluis** [comment] 2022-01-04 13:09
Duplicate of #1514

**Comment by jfversluis** [comment] 2022-01-04 13:09
And many others :) but please refer to the linked issue above for a proposal to move forward on this. Thanks!

**Closed by jfversluis** 2022-01-04 13:09 UTC
Labels: bug

**Comment by symbiogenesis** [comment] 2022-11-06 00:05
[This comment](https://github.com/xamarin/Essentials/issues/1562#issuecomment-770353589) makes it sound like the PNG conversion is the issue.

Would merging this PR help: https://github.com/xamarin/Essentials/pull/1747
