### ISSUE TITLE
[iOS-XF] NRE at FileBase.PlatformGetContentType (System.String extension)

### ISSUE THREAD

**Issue by nativenolde** [xamarin/Essentials#753] opened 2019-03-29 14:17 UTC
Recently i enabled the experimental email attachment feature
`ExperimentalFeatures.Enable(ExperimentalFeatures.EmailAttachments);`
so that my xf-app is able to send some diagnostic informations as an email attachment. The file itself should be called: Diagnostics_20190329T135236.dat (for example, it uses the current timestamp).

On Android it works fine, but on iOS an NullReferenceException happens, as you can see enclosed. Im not sure if thats relevant for you, since the feature is still in preview.

- Version with issue:
- IDE: Visual Studio 2019 RC4
- Platform Target Frameworks:
  - iOS: 12.2
  - Android: 9.1
- Nuget Packages:
  - Microsoft.AppCenter.Analytics: 1.14.0
  - Microsoft.AppCenter.Crashes: 1.14.0
  - Microsoft.AppCenter.Push: 1.14.0
  - Prism.DryIoc.Forms: 7.1.0.431
  - sqlite-net-pcl: 1.5.231
  - Xam.Plugin.Geolocator: 4.5.0.6
  - Xam.Plugin.Media: 4.0.1.5
  - Xam.Plugins.Settings: 4.0.0.7
  - Xamarin.Essentials: 1.1.0
  - Xamarin.Forms: 3.6.0.264807
- Affected Device:
  - model: iPhone 10,4
  - oemName: Apple
  - osName: iOS
  - osVersion: 12.2
  - osBuild: 16E227
  - locale: de_DE
  - timeZoneOffset: 60
  - screenSize: 1334x750
  - carrierName: Telekom.de
  - carrierCountry: de
  - wrapperRuntimeVersion: 11.2.0

### Screenshots
![App Center Screenshot](https://user-images.githubusercontent.com/45496636/55238774-98b12000-5235-11e9-88a4-99c36f4be607.png)

### Error report
[report.zip](https://github.com/xamarin/Essentials/files/3023026/report.zip)

**Comment by nativenolde** [comment] 2019-03-29 17:54
As it turns out, the root cause seems to be the .dat file extension. It works if i change it to .zip

**Comment by jamesmontemagno** [comment] 2019-03-29 18:01
Interesting... we can try to reproduce it with the .dat and try not to throw an exception, but iOS may only support certain file types.

**Comment by Mrnikbobjeff** [comment] 2019-04-11 09:46
So, .dat Files are of the mime type "application/octet-stream", the reason we get a nre is that UTType.CreatePreferredIdentifier returns null if it can not get the identifier for the given parameters. https://developer.apple.com/documentation/coreservices/1448939-uttypecreatepreferredidentifierf  
Wenn could either fallback to the default mime type (which coincidentally matches the expected mime type here) if iOS can not recognise the mime type, otherwise we could go the way of Apache tika and embedan XML file containing a dictionary to lookup mime types from file endings, which would also have the benefit of giving us constant results across all platforms

**Comment by jamesmontemagno** [comment] 2019-04-18 02:10
so it seems like this can be handled today if you set the ContentType on the file. I think this just needs to be documented.

**Comment by jamesmontemagno** [comment] 2019-04-29 15:35
Closing due to expected functionality.

**Closed by jamesmontemagno** 2019-04-29 15:35 UTC
