### ISSUE TITLE
Geolocation GetLocationAsync permission exception

### ISSUE THREAD

**Issue by Draco94** [xamarin/Essentials#634] opened 2018-12-05 12:24 UTC
### Description
Not sure if I am doing something wrong or this is a bug. 
I grant location permission on a main thread but after that when I use following:

           var location = await Geolocation.GetLocationAsync(); 

wrapped in a async task it throws PermissionException pEx with message: "Permission request must be invoked on main thread.".

I already granted permission so why does it throws this exception?

Permission is asked with Plugin.Permissions;
For IOS and Windows platform this is untested.

### Steps to Reproduce
1. Create a page where you request permission on a main thread.
2. Create second page that displays location lat, long in label.. 
Code behind:  async task with: await Geolocation.GetLocationAsync(); | code block (including try/except)
3. When Granted on page 1 navigate to page 2 and run the task.

### Expected Behavior
Should show lat, long since permission is granted.
### Actual Behavior
Permission ex : "Permission request must be invoked on main thread.".
### Basic Information

- Version with issue: 0.11.0 preview, 1.0
- Last known good version: 0.10.0 preview
- IDE:
- Platform Target Frameworks: 
  - iOS:  Not Tested
  - Android: API 26
  - UWP: Not Tested
- Android Support Library Version: 
- Nuget Packages: All default updated packages and Plugin.Permissions;
- Affected Devices: Tested on Samsung Galaxy S7

### Screenshots
Permission request:
![image](https://user-images.githubusercontent.com/31309016/49513232-94c94e80-f890-11e8-9e0b-fa449d136241.png)

Task Execution: 
![image](https://user-images.githubusercontent.com/31309016/49513321-ea9df680-f890-11e8-80ad-bea69ea495f6.png)

**Comment by pictos** [comment] 2018-12-05 20:05
I think you don't need to ask permition, the Essential does that for you

**Comment by Draco94** [comment] 2018-12-05 20:22
Of course. But if permission is already granted it will try to fetch latitude, longitude and altitude. In this scenario it throws exception "Permission request must be invoked on main thread.". I granted permission already. If I let Essential ask for permission from within task it's normal behavior to throw exception since is not UI thread. Lets say I want to perform some background work that make use of X.E Geolocation from time to time.

**Comment by pictos** [comment] 2018-12-05 21:55
Ok, try use `async void` instead `Task.Run`. As you are doing the request inside an event it is ok to use `async void`

**Comment by Draco94** [comment] 2018-12-05 22:16
I know that it will work with async void. I intentionally want to run in a task. In example is just button click event that demonstrates the problem. As long it's in a task no matter how you invoked the task it will still throw same exception.

**Comment by Draco94** [comment] 2018-12-06 08:50
It seems to be working. Thank you for your time.

**Comment by Draco94** [comment] 2018-12-06 12:33
Hi again, it doesn't seem to work if you use another thread.

`void RequestLocation(object sender, EventArgs e)
        {
            new Thread(async () =>
            {
                Thread.CurrentThread.IsBackground = true;

                try
                {
                    var task = Geolocation.GetLocationAsync();
                    await task.ContinueWith(x =>
                    {
                        var location = x.Result;
                        if (location != null)
                            DisplayAlert("Localização", $"latitude:{location.Latitude}, logintude:{location.Longitude}", "OK");

                    });
                }
                catch (Exception ex)
                {
                    throw ex;
                }
            }).Start();
        }`

This for example throws exception "System.AggregateException: One or more errors occurred."
This was working in essential version 0.10.0 preview.

**Comment by Draco94** [comment] 2018-12-06 13:14
I want to do some work in thread that includes Geolocation.GetLocationAsync(); 
This thread will run occasionally to collect latitude and longitude and save them to database.
I've seen release notes for version 0.11.0 and this is some of the issues closed #621.
Now I thought that #621 is related only when you're requesting the permission. So if permission dialog happen it must be on UI thread. Since I allowed it in UI thread when I after want to get latitude and longitude in a thread problems happen.

**Comment by pictos** [comment] 2018-12-06 14:15
Hi @Draco94 , the multi-thread can be complex to handle...  When you use `new Thread(() =>{});` you run your code in background thread, and the request permission too, so you get an Exception. If you want to get the location periodically you can use the [Device.StartTimer](https://docs.microsoft.com/en-us/dotnet/api/xamarin.forms.device.starttimer?view=xamarin-forms)

**Comment by jamesmontemagno** [comment] 2018-12-07 01:19
We also only allow you to call this from the UI thread in 1.0 when you need to get permissions. This is as designed.

**Comment by jamesmontemagno** [comment] 2018-12-07 01:41
Closing as this is the expected behavior. You should check to ensure you have permission before calling.

**Closed by jamesmontemagno** 2018-12-07 01:41 UTC

**Comment by klzig** [comment] 2018-12-07 06:17
FWIW--
I did initialize stuff.
I did check to ensure I have permission before calling.
Here's an example that will reproduce for Android, iOS, and UWP:
```
Task.Run(
   async () =>
   {
      var request = new GeolocationRequest(GeolocationAccuracy.High, new TimeSpan(0, 0, 4));
      var location = await Geolocation.GetLocationAsync(request); 
   });
```

I'm hitting the following throw in the Permissions class:

 ```
internal static Task<PermissionStatus> RequestAsync(PermissionType permission)
        {
            if (!MainThread.IsMainThread)
                throw new PermissionException("Permission request must be invoked on main thread.");

            return PlatformRequestAsync(permission);
        }

```

I don't think this will ever work from anything but the main thread, regardless whether I check for permissions before calling.
For now I don't need to be running this in a background thread, will refactor.

**Comment by jamesmontemagno** [comment] 2018-12-07 14:22
What version of the plugin are you using @klzig

**Comment by jamesmontemagno** [comment] 2018-12-07 14:23
@redth are we missing PRs from https://github.com/xamarin/Essentials/tree/dev/api-fix

**Comment by Draco94** [comment] 2018-12-07 14:42
I noticed this happening on version 0.11.0 preview and 1.0.0.

**Comment by klzig** [comment] 2018-12-07 14:48
I'm on 1.0.0.  Thanks.

**Comment by jamesmontemagno** [comment] 2018-12-07 16:04
Will be fixed in 1.0.1 as we missed a pr into a different branch.

**Comment by klzig** [comment] 2018-12-07 16:08
Cool, thanks for the attention and the awesome plugin.

**Comment by jamesmontemagno** [comment] 2019-02-05 18:47
If you don't have permission it will still try to prompt the user on the main thread:
https://github.com/xamarin/Essentials/blob/master/Xamarin.Essentials/Permissions/Permissions.android.cs#L104
This is the correct design. You can use my https://github.com/jamesmontemagno/PermissionsPlugin to check before calling.

**Comment by mo-kml** [comment] 2019-02-06 06:16
Hi @jamesmontemagno 
Thank you for your response
But i did try that and got permission from user by permission plugin
but still it throw this exception.
you should know that if i use it in a regular view it works perfectly but in popup it throws this error

**Comment by jamesmontemagno** [comment] 2019-02-09 08:47
Can you give me a repro sample please @mo-kml

**Comment by andrewchungxam** [comment] 2019-02-18 18:14
(Ran into similar issues (permissions not prompted but run from a ViewModel page.)  In case it's helpful to someone - I've put the following solution below:

https://stackoverflow.com/questions/54719461/geolocation-getlastknownlocationasync-permission-exception-from-xamarin-forms/54719574#54719574

**Comment by HenKun** [comment] 2019-03-05 13:41
Same issue here, running 1.0.1. Permission is already granted (I double-checked it), but when `GetLastKnownLocationAsync` is called from other than the main thread the exception occurs:

```
Permission request must be invoked on main thread.

  at Xamarin.Essentials.Permissions.RequestAsync (Xamarin.Essentials.PermissionType permission) [0x00007] in C:\agent\_work\69\s\Xamarin.Essentials\Permissions\Permissions.shared.cs:18 
  at Xamarin.Essentials.Permissions+<RequireAsync>d__3.MoveNext () [0x0000a] in C:\agent\_work\69\s\Xamarin.Essentials\Permissions\Permissions.shared.cs:25 
--- End of stack trace from previous location where exception was thrown ---
  at Xamarin.Essentials.Geolocation+<PlatformLastKnownLocationAsync>d__6.MoveNext () [0x00017] in C:\agent\_work\69\s\Xamarin.Essentials\Geolocation\Geolocation.android.cs:22 
--- End of stack trace from previous location where exception was thrown ---
  at XY.UserLocationProvider+<GetLastLocationAsync>d__0.MoveNext () [0x00038] in XY\UserLocationProvider.cs:20 
```

Even if this issue is solved, and the PermissionException only occurs when the permission really has to be requested, it is still some kind of confusing. Because we never know if permission was already granted, we either have to

a) Always check for permission ourself before invoking GeoLocation (which would make the internal permission handling senseless)

or b) Use the solution given in the link by @andrewchungxam which is not that beautiful because `Geolocation.GetLastKnownLocationAsync` will always run on the main thread, even if not required.

Wouldn't it be better to either

a) Remove the internal permission handling in GeoLocation and state that everyone has to care for the permissions themselves

or b) Use `Device.BeginInvokeOnMainThread` within GeoLocation when really required?

**Comment by SagarPanwala** [comment] 2019-05-08 03:57
I'm using version 1.1.0. 
`try
            {
                var request = new GeolocationRequest(GeolocationAccuracy.Medium);
                var location = await Geolocation.GetLocationAsync(request);

                if (location != null)
                {
                    Location = string.Format("{0}{1}{2}", "Latitude: " + location.Latitude.ToString(), 
                             System.Environment.NewLine, "Longitude: " + location.Longitude.ToString());
                }
            }
            catch (FeatureNotSupportedException fnsEx)
            {
                //await DisplayAlert("Faild", fnsEx.Message, "OK");
            }
            catch (PermissionException pEx)
            {
                //awaits NavigationServices.DisplayAlert(string.Empty, "Please give location permission", "OK");
            }
            catch (Exception ex)
            {
                //await DisplayAlert("Faild", ex.Message, "OK");
            }`
I have above code in Page OnAppearing method.
When I run the app , this code asks Popup for Permission.
if I deny then again page OnAppearing is getting called, but this time this code not asks for permission.
if I put app in background and open again. 
Page OnAppearing method is getting call, above code is also executed, but it is not asking for permission popup.

**Comment by pictos** [comment] 2019-05-08 16:34
@SagarPanwala the permission pop-up doesn't show because you have try to update the UI from background thread. Take care about that.

 @jamesmontemagno, can we guarantee the permission will be run in MainThread? I think if this lines `await Permissions.RequireAsync(PermissionType.LocationWhenInUse);` runs in Main Thread this trouble doesn't happens.

**Comment by SagarPanwala** [comment] 2019-05-08 16:42
Hi,
How can you say I tried to get it in background thread?
I normally do api call like this and it updates UI also.
Can you please explain how can I debug my code called from background
thread or from main thread?

**Comment by pictos** [comment] 2019-05-08 20:41
@SagarPanwala you can use this helper class.
```csharp
 public static class ThreadHelper
    {
        static bool IsMainThread => !Thread.CurrentThread.IsBackground;

        public static void WhatThreadAmI([CallerMemberName] string method = "", [CallerLineNumber] int line = 0)
        {
            if (Thread.CurrentThread.IsBackground)
                System.Console.WriteLine("\t In background");

            Console.WriteLine("################");
            Console.WriteLine($"{method} : line {line}, is on MainThread:{IsMainThread}");
            Console.WriteLine("################");
        }
    }
```

And just put the method` WhatThreadAmI()`. [Reference](https://youtu.be/jgxJbshvCXQ?list=PL3GeZ8t0AGwwU2U34K7v0oXK4Vv28OdZ5)

**Comment by SagarPanwala** [comment] 2019-05-10 03:37
@pictos  : this is certainly not the case. I'm now doing thing on button click, so call is being made in Main Thread. Permission popup only shows first time, if I deny , after that it is not showing at all. I must have to restart the application.

**Comment by pictos** [comment] 2019-05-10 13:07
@SagarPanwala how did you implemented this? Someone had the similar issue, and I suggest [this snippet](https://github.com/xamarin/Essentials/issues/634#issuecomment-444691233)

**Comment by pldeschamps** [comment] 2020-05-05 19:38
I had this issue recently and solved it by making one of these changes in the Android project properties, Android options tab:
- uncheck "Use incremental Android packaging system (aapt2)
- uncheck "Use the concurrent garbage collector"
- Linking : "Sdk Assemblies Only" instead of "None"

**Comment by Stensan** [comment] 2020-09-04 09:31
This problem still exists. I solved it by asking for the location permission beforehand.

**Comment by IeuanWalker** [comment] 2021-03-03 18:45
@jamesmontemagno @pictos 
I'm also having this issue, and it seems specific to the get geolocation.

This is my code - 
```csharp
Xamarin.Essentials.Location position = await Geolocation.GetLocationAsync(new GeolocationRequest(GeolocationAccuracy.Default, TimeSpan.FromSeconds(1.5)));
return new GpsPosition
{
    Longitude = position.Longitude,
    Latitude = position.Latitude
};
```

I'm using Plugin.Media package and calling `TakePhotoAsync` API and `PickPhotoAsync` API, both are handling the permission fine, but the geolocation in essentials is throwing this exception.

**Comment by pictos** [comment] 2021-03-03 22:07
@IeuanWalker I think that you should open a new issue to have better visibility.

**Comment by jrahma** [comment] 2021-04-12 23:13
Same problem
