### ISSUE TITLE
Feature Request: Bio Metric Authentication Type in device info

### ISSUE THREAD

**Issue by joshwl2003** [xamarin/Essentials#762] opened 2019-04-11 18:07 UTC
### Description
It would be great if device info could include what type of bio metrics sign on is available. Touch, Face ID, none and anything else that makes sense for a specified platform.

In iOs LAContext() contains this information.
On Android  use the BiometricManager

**Comment by jamesmontemagno** [comment] 2019-04-25 01:59
Duplicate of: https://github.com/xamarin/Essentials/issues/71

**Closed by jamesmontemagno** 2019-04-25 01:59 UTC
