### ISSUE TITLE
[Enhancement] Redundant allocation in TextToSpeech.Android

### ISSUE THREAD

**Issue by Mrnikbobjeff** [xamarin/Essentials#965] opened 2019-10-30 03:53 UTC
### Description
The c# spec allows anonymous functions delegates to be cached, method group conversions may not be cached though and have to be allocated delegate instances every time. We have several instances in Xamarin.Essentials where we use method group conversions for brevity allowing them to allocate unnecessarily.

**Comment by mattleibow** [comment] 2020-11-06 01:34
Duplicate of https://github.com/xamarin/Essentials/issues/1029

**Closed by mattleibow** 2020-11-06 01:34 UTC
Labels: enhancement
