### ISSUE TITLE
[Bug] Geocoding API 23 Android 6.0 no answer

### ISSUE THREAD

**Issue by Scantraxx123** [xamarin/Essentials#891] opened 2019-08-22 20:53 UTC
### Description
I implemented the Geocoding Service from here. https://docs.microsoft.com/en-gb/xamarin/essentials/geocoding?tabs=android
I want to get the City, where the Smartphone is in that moment. But my Emulator with Android Version 6.0 don't get an answer. After I saw that I don't get an answer from the service, I tried it with the API Versions after Android 6.0 and there it works.

### Expected Behavior
Answer from Geocoding Service

### Actual Behavior
Only answer for 7.0+ API

### Basic Information

- Version with issue: Xamarin.Forms 4.10555618 and 4.20709249
- Last known good version: unknown
- IDE: VS 2019 Community, Version: 16.2.3
- Platform Target Frameworks: Android: 6.0 to 9.0
- Nuget Packages:
- Affected Devices:

### Reproduction Link

https://docs.microsoft.com/en-gb/xamarin/essentials/geocoding?tabs=android

**Comment by newky2k** [comment] 2019-08-30 15:18
@Scantraxx123  what version of Xamarin.Essentials are you using?

**Comment by Scantraxx123** [comment] 2019-08-30 17:53
I used Version 1.2 and 1.3. On both versions it doesn't work.

**Comment by newky2k** [comment] 2019-09-02 18:51
@Scantraxx123  can you please provide the code you are using to call the API so i can investigate further.

**Comment by Scantraxx123** [comment] 2019-09-03 08:15
` private async Task locationAsync()
        {

            var request = new GeolocationRequest(GeolocationAccuracy.Medium);
            var location = await Geolocation.GetLocationAsync(request);

            if (location != null)
            {
                var placemarks = await Geocoding.GetPlacemarksAsync(location.Latitude, location.Longitude);

                var placemark = placemarks?.FirstOrDefault();
                if (placemark != null)
                {
                    Location.Text = placemark.Locality;
                    ConstantController.ACTUALLOC = placemark.Locality;

                }
            }

        }`

**Comment by jamesmontemagno** [comment] 2019-12-20 00:01
Unable to reproduce here. It is possible that some emulators do not have geocoding services as they make a request to geocoders themselves from the providers. This will throw an exception if so. Closing as it is possible to not get any results.

**Closed by jamesmontemagno** 2019-12-20 00:01 UTC
Labels: bug, need-more-information
