### ISSUE TITLE
[Bug] ShareFileRequest.Title does not work on Android when sharing via email

### ISSUE THREAD

**Issue by vg12345** [xamarin/Essentials#1690] opened 2021-02-13 17:19 UTC
ShareFileRequest.Title does not work on Android.
When sharing to email, the subject field remains empty. 
(Works as expected on iOS and UWP: the subject is not empty and identical to Title)

await Share.RequestAsync(new ShareFileRequest
{
    Title = "Some email subject example",
    File  = new ShareFile(path)
});

VisualStudio 2019 (v.16.8.5)
Xamarin.Essentials (v. 1.6.1)

**Comment by dimonovdd** [comment] 2021-02-13 22:28
I think these issues are related
https://github.com/xamarin/Essentials/issues/858

**Comment by jamesmontemagno** [comment] 2021-04-13 20:23
Yes, the title is on the share sheet itself not for text. Duplicate of #858  as @dimonovdd mentioned.

**Closed by jamesmontemagno** 2021-04-13 20:23 UTC
Labels: bug
