### ISSUE TITLE
[Enhancement] Give users to ability to share files from memory stream without having to pull from directory

### ISSUE THREAD

**Issue by nichojo89** [xamarin/Essentials#1495] opened 2020-11-04 18:24 UTC
## Summary
Could we give the ShareFile object a byte[] parameter or MemoryStream parameter or FileStream parameter? This would give us the ability to share documents such as large pdf's without required the user to save to cache

## API Changes

Xamarin.Essentials.ShareFile will accept one of the described parameters

`var byteArray  = new byte[1];
                using (var fs = new FileStream("FileName", FileMode.Create, FileAccess.Write))
                {
                    fs.Write(byteArray, 0, byteArray.Length);
                    await Share.RequestAsync(new ShareFileRequest
                    {
                        Title = Title,
                        File = new ShareFile(fs)
                    });
                    await Share.RequestAsync(new ShareFileRequest
                    {
                        Title = Title,
                        File = new ShareFile(byteArray)
                    });
                }`

## Intended Use Case
Apps can share files without saving them any sort of directory

**Comment by mattleibow** [comment] 2020-11-06 01:29
I do not believe this is possible on Android and possibly Tizen.

**Comment by mattleibow** [comment] 2020-11-06 01:50
Duplicate of #955

**Closed by mattleibow** 2020-11-06 01:50 UTC
Labels: feature-request
