### ISSUE TITLE
Local Notifications 

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#624] opened 2018-11-18 18:37 UTC
Please add an option within Xamarin Essential to enable users to send local notifications without having to use notifications services such as OneSignal

Many times uses want to send local notifications for this device itself, e.g. reminders apps, spirts app, locations app..

For example if I want to send notification to the user when they reach a specific location then why do I need to connect to notification serivice?

**Comment by Redth** [comment] 2018-11-26 15:13
Duplicate of #238

**Closed by Redth** 2018-11-26 15:13 UTC
Labels: duplicate
