### ISSUE TITLE
ITMS-90809: Deprecated API Usage 

### ISSUE THREAD

**Issue by Sebastian1989101** [xamarin/Essentials#897] opened 2019-09-01 21:34 UTC
After uploading my app to ITC (Apple), I get the following message after including Xamarin.Essentials to it: 

> Dear Developer,   We identified one or more issues with a recent delivery for your app,   "MyApp" 1.0.0 (19200). Your delivery was successful,   but you may wish to correct the following issues in your next delivery:    ITMS-90809: Deprecated API Usage - Apple will stop accepting   submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview   for more information.    After you’ve corrected the issues, you can use Xcode or Application Loader   to upload a new binary to App Store Connect.    Best regards,   The App Store Team

**Comment by Redth** [comment] 2019-09-03 18:17
I don't believe we use `UIWebView` in Essentials' code at all.  Perhaps this warning is coming from your Xamarin.Forms usage, or some other component?

**Comment by Sebastian1989101** [comment] 2019-09-03 18:19
@Redth I only use Xamarin.Forms (4.2 currently) and Xamarin.Essentials in this app. Also I can say for sure that my app does not use UIWebView at any point. 

Is there any way (except Ctrl+F) to search for UIWebView references in the whole code (and libraries)?

**Comment by jamesmontemagno** [comment] 2019-09-03 18:52
We do not use UIWebView at all. 

Are you using the Xamarin.Forms WebView? You would want to enable: https://docs.microsoft.com/en-us/xamarin/xamarin-forms/user-interface/webview?tabs=windows#performance

**Comment by jamesmontemagno** [comment] 2019-09-03 18:54
If you have the final .app you could bust it open and find your main DLL and open it in VS for Mac or DotPeek and see the references in there.

**Comment by Sebastian1989101** [comment] 2019-09-03 19:03
@jamesmontemagno And for what kind of reference do I have to look for? Because UIWebView is in UIKit / Xamarin.iOS.dll which is probably referenced in nearly any iOS project.

**Comment by Redth** [comment] 2019-09-03 19:13
Yeah looks like it's not being linked out in [Xamarin.Forms](https://github.com/xamarin/Xamarin.Forms/search?q=UIWebView&unscoped_q=UIWebView).  What do you have your linker settings for the iOS app set to?

**Comment by SebastianKruseWago** [comment] 2019-09-04 15:56
@Redth linking is set to "Link Framework SDK only" on any project. Plus this problem only occurs for one of my projects even if this project is just a copy of another project with a different SQLite and different images (no changes in the code at all, this project exists 4 times and only one of them is causing this problem). 

The problem is, this is a total blocker problem because I cannot submit it to the AppStore until I have fixed this. The targeted release is already next week and I have no idea how I can fix it.

**Comment by merckxite** [comment] 2019-09-05 21:48
@SebastianKruseWago Apple hasn't yet stopped accepting apps using these API's, check to see if your build has come up in App Store Connect and if it hasn't it is likely another issue. I've been shipping builds daily this week and while they've all had this error, my builds have still gone through. Haven't yet deduced for sure whether this is an Essentials problem in my project.

**Comment by jamesmontemagno** [comment] 2019-09-09 18:01
Closing this out as it is over on the Xamarin.Forms github: https://github.com/xamarin/Xamarin.Forms/issues/7323

**Closed by jamesmontemagno** 2019-09-09 18:01 UTC
Labels: bug, need-more-information

**Comment by MohamedMabroukDev** [comment] 2019-10-03 10:31
hi all ,
when i check latest version of xamarin forms i found that they fix the error. (4.2.0.815419)

**Comment by pulmuone** [comment] 2020-05-28 06:34
Xamarin.iOS.dll
It seems to use UIKit.UIWebView in AVFoundation.AVPlayerLayer.

--------------------------------------------------
<member name="T:AVFoundation.AVPlayerLayer">
      <summary>A type of <see cref="T:CoreAnimation.CALayer" /> on which a <see cref="T:AVFoundation.AVPlayer" /> renders its output.</summary>
      <remarks>
        <para>
          <see cref="T:AVFoundation.AVPlayerLayer" /> objects may be used for AV playback in a variety of situations where a heavier-weight component such as <see cref="T:UIKit.UIWebView" /> would be unnecessary or unavailable (such as on tvOS).</para>
        <para>The following example shows how a <see cref="T:AVFoundation.AVPlayerLayer" /> can be used to stream a Web video:</para>
        <example>
          <code lang="C#"><![CDATA[
var src = NSUrl.FromString("https://somevideo");
var asset = AVAsset.FromUrl (src);
var playerItem = new AVPlayerItem (asset);
var player = new AVPlayer (playerItem);
var playerLayer = AVPlayerLayer.FromPlayer (player);
var frame = new CGRect (0, 0, this.View.Frame.Width, this.View.Frame.Height);
playerLayer.Frame = frame;
this.View.Layer.AddSublayer (playerLayer);
player.Play ();
    ]]></code>
        </example>
      </remarks>
      <related type="PlatformDocAPI" href="https://developer.apple.com/library/ios/documentation/AVFoundation/Reference/AVPlayerLayer_Class/index.html">Apple documentation for <c>AVPlayerLayer</c></related>
    </member>
