### ISSUE TITLE
[Enhancement] warning MSB3277: Found conflicts between different versions of "System.Numerics.Vectors" that could not be resolved

### ISSUE THREAD

**Issue by tranb3r** [xamarin/Essentials#1083] opened 2020-02-06 18:13 UTC
### Description

When using both Xamarin.Essentials and System.Text.Json in a xamarin forms app, I get this warning when building the app for android:
`warning MSB3277: Found conflicts between different versions of "System.Numerics.Vectors" that could not be resolved`

I don't know if this is an issue with Xamarin.Essentials or with System.Text.Json. Or something else. And I don't know how to investigate it, so any help would be much appreciated :)
Also, I don't understand why the android project references its own System.Numerics.Vectors dll. Could anyone point me to some documentation with an explaination ?

### Steps to Reproduce

1. Create a blank xamarin forms app
2. Add System.Text.Json nuget package (4.7.0) to the netstandard library containing the app code
2. Xamarin.Essentials should already be referenced. If not add it as well.
4. Build the android app

### Expected Behavior

The android app should build without any error or warning.

### Actual Behavior

The android app builds successfully, but with this warning:
`warning MSB3277: Found conflicts between different versions of "System.Numerics.Vectors" that could not be resolved`

No warning if I remove Xamarin.Essentials or System.Text.Json.

### Basic Information

- Version with issue: 1.4.0-pre2
- Last known good version: unknown
- IDE: Visual Studio 2019 16.5.0-pre2
- Platform Target Frameworks:  Android: 10
- Android Support Library Version: N/A
- Nuget Packages: Xamarin.Essentials + System.Text.Json

**Comment by jamesmontemagno** [comment] 2020-02-07 16:17
On a file-> new project with 14.0-pre2 I don't seem to get any warnings on VS 2019.

After installing system.text.json I do get this warning. This is most likely because they have referenced the nuget and we reference the dlls as they included there. I will re-validate with the teams, but it should not cause any issues.

**Comment by jamesmontemagno** [comment] 2020-03-03 18:31
My thinking is that if you remove both references to System.Numerics and System.Numerics.Vectors that the warning will go away and it should work alright because it brings in the nuget package.... perhaps we should switch to having this as a dependency instead of the dlls....

**Comment by auriou** [comment] 2020-04-01 12:06
It seems that Json.Text.Json does not work on xamarin.ios
https://github.com/dotnet/runtime/issues/31326

It is a shame to share its Models (into separate lib netstandard) between its client application and the webapi and especially for the properties of attributes and libs references

Newtonsoft: [JsonProperty ("id")]

System.text.json [JsonPropertyName ("id")]

**Comment by jamesmontemagno** [comment] 2020-04-01 20:52
Closing as duplicate of #904 that has more info

**Closed by jamesmontemagno** 2020-04-01 20:52 UTC
Labels: enhancement
