### ISSUE TITLE
PhoneDialer needs equivalent of CanMakePhoneCall

### ISSUE THREAD

**Issue by jonathanpeppers** [xamarin/Essentials#193] opened 2018-04-20 16:21 UTC
### Description

I ported usage of `Xam.Plugin.Messaging` to `Xamarin.Essentials.PhoneDialer` in the [Evolve 2016 app](https://github.com/jonathanpeppers/app-conference/commits/xamarin-essentials).

There appears to be no equivalent to:
```csharp
public bool CanMakePhoneCall => CrossMessaging.Current.PhoneDialer.CanMakePhoneCall;
```

There are some internal APIs named `IsSupported`. Maybe this is something that needs exposed across the board?

Right now all a developer can do it `try-catch` on `FeatureNotSupportedException`.

### Steps to Reproduce

1. Port an app from using `Xam.Plugin.Messaging` to `Xamarin.Essentials.PhoneDialer`
2. Try to implement a feature where you disable/hide a button when a device doesn't support phone calls

### Expected Behavior

There should be some public API for `PhoneDialer.IsSupported`. And maybe other APIs as well?

### Actual Behavior

You have to `try-catch` `FeatureNotSupportedException`.

### Basic Information

- Version with issue: 0.0.1.79-preview

### Reproduction Link

Commit [here](https://github.com/jonathanpeppers/app-conference/commit/947c5c1148ca8c3defbe9368eeb05f2b55def715).

**Comment by jamesmontemagno** [comment] 2018-04-24 15:35
Duplicate of #77, to continue discussion there.

**Closed by jamesmontemagno** 2018-04-24 15:35 UTC
Labels: proposal
