### ISSUE TITLE
Enhancement:  Add the ability to Share a file in the Xamarin.Essentials.Share

### ISSUE THREAD

**Issue by solomonfried** [xamarin/Essentials#695] opened 2019-01-31 23:30 UTC
Bug report best practices: [Submitting Issues](https://github.com/xamarin/Essentials/blob/master/SUBMITTING-ISSUES.md)

### Description
Feature request Add the ability to Share a file in the Xamarin.Essentials.Share

The current version of Share only supports sharing text and URI.
Supporting File sharing would resolve many issues user have with saving files outside of the Local App Data space.

It would be supported by added a new class
ShareFileRequest {
   string FilePath;
   string ContentType;
  string Title;
}

It would be called using Share.RequestAsync(new ShareFileRequest());

An example of how to implement a file share is here (I have not tried this)
https://www.syncfusion.com/kb/8707/how-to-share-the-pdf-document-in-xamarin-forms-platform

### Steps to Reproduce

1. 
2. 
3. 

### Basic Information

- Version with issue:
- Last known good version:
- IDE:
- Platform Target Frameworks: 
  - iOS:  
  - Android:  
  - UWP:   
- Android Support Library Version: 
- Nuget Packages:
- Affected Devices:

**Comment by mattleibow** [comment] 2019-02-01 00:00
This is most probably coming with #416

**Comment by jamesmontemagno** [comment] 2019-02-04 16:03
Duplicate of: https://github.com/xamarin/Essentials/issues/425

**Closed by jamesmontemagno** 2019-02-04 16:03 UTC
