### ISSUE TITLE
Data Transfer: Share Image with Title and URL

### ISSUE THREAD

**Issue by jrahma** [xamarin/Essentials#424] opened 2018-07-28 05:17 UTC
Hi,

Please add an option to Share Image with a Title and URL..

Thanks,
Jassim

**Comment by mattleibow** [comment] 2018-08-15 15:54
This probably is going to be related to #425 #416

**Comment by Redth** [comment] 2018-11-26 14:32
Duplicate of #425

**Closed by Redth** 2018-11-26 14:32 UTC

**Comment by abdul-wasey** [comment] 2020-09-12 22:01
You can achieve this functionality by writing some platform specific code .
I write a function that takes uri, message and bytes[] of image as arguments.
Here is the sample code for android.
```csharp
public async Task Share(string uri, string message, byte[] bytes)
        {
            var intent = new Intent(Intent.ActionSend);
            intent.PutExtra(Intent.ExtraOriginatingUri, uri);
            intent.PutExtra(Intent.ExtraText, message);
            intent.SetType("image/png");

            var path = Android.OS.Environment.GetExternalStoragePublicDirectory(Android.OS.Environment.DirectoryDownloads
                + Java.IO.File.Separator + "logo.png");

            await File.WriteAllBytesAsync(path.AbsolutePath, bytes);
            intent.PutExtra(Intent.ExtraStream, Android.Net.Uri.FromFile(path));
            Forms.Context.StartActivity(Intent.CreateChooser(intent, "Here you go ;)"));
}
```
