### ISSUE TITLE
[Enhancement] Secure Storage - Support for Get & Set without Async

### ISSUE THREAD

**Issue by kberawala** [xamarin/Essentials#1157] opened 2020-03-08 23:35 UTC
## Summary
Please enable secure storage to support non-async calls

## API Changes
Xamarin.Essentials.SecureStorage.Set(stringKey, stringValue);
string readValue = Xamarin.Essentials.SecureStorage.Get(stringKey);

## Intended Use Case
To be able to read/write values in page constructors, background services/workers, push notification on message received, etc.

**Comment by jamesmontemagno** [comment] 2020-03-09 14:34
Duplicate of : https://github.com/xamarin/Essentials/issues/494 pretty much we require Async due to underlying platforms.

**Closed by jamesmontemagno** 2020-03-09 14:34 UTC
Labels: feature-request
