### ISSUE TITLE
[Bug] IsFirstLaunchEver is true if app is minimized and then relaunched (Android)

### ISSUE THREAD

**Issue by mpanzica** [xamarin/Essentials#1398] opened 2020-09-28 15:39 UTC
### Description
On Android, IsFirstLaunchEver always returns true if the app, upon the first launch, is sent to background (not killed)

### Steps to Reproduce
`public App() {`
`    // other stuff`
`    VersionTracking.Track();`
`    System.Diagnostics.Debug.Print($">>>>> IS FIRST LAUNCH EVER? {VersionTracking.IsFirstLaunchEver}");`
`}`

1. Launch app for the first time. IsFirstLaunchEver returns true. 
2. Send app to the background (press Back button - do not kill the app.
3. Open the App drawer and tap on the app icon (do not resume from task list)
4. IsFistLaunchEver still returns true.

IsFirstLaunchEver returns false if the app is killed instead.

### Expected Behavior
The second time VersionTracking.Track() is called IsFirstLaunchEver should be reset to false.

### Actual Behavior
Any subsequent call to IsFirstLaunchEver returns true unless the app is killed.

- Version with issue: 1.5.3.2
- Last known good version: unknown

**Comment by jamesmontemagno** [comment] 2020-09-28 16:57
Yes, this is the correct functionality. It is for the entire instance in which the app has been running until the user closes it. This functionality matches on all of the platforms. Thoughts @mattleibow?

I do something like this:

```csharp
        bool showDisclaimer = true;

        protected override async void OnAppearing()
        {
            base.OnAppearing();
            if(VersionTracking.IsFirstLaunchEver && showDisclaimer)
            {
                showDisclaimer = false;
                await DisplayAlert("Disclaimer",
                    "If you start to experience pain during these exercises please stop the stretches and seek medical attention.", "OK");
            }
        }
```

**Comment by mattleibow** [comment] 2020-09-28 17:38
That is correct. The tracking is caching everything for a single app run.

Pressing back is not actually closing the app, it is going home. The use may wish to return. 

The actual issue might be that a new instance of App should not be recreated every time. I would maybe suggest caching that as a static field. @PureWeen might actually have a recommendation on this...

**Comment by mpanzica** [comment] 2020-09-28 18:08
Thanks for your prompt reply.
@jamesmontemagno I use a similar approach on my App class. Unfortunately a few other objects behave differently on first run (I am thinking of coach marks on pages, for example). Since I am not willing to duplicate the code on each class, I am forced to make this piece of information publicly available to other objects.
I assumed that if VersionTracking.Track() was called again, for whatever reason, the flag would change to false.
Another option would be a "Commit" command to be invoked upon sleep: that would not break any existing code, while allowing us to use just a single call to check whether app is on its first run.

**Comment by mattleibow** [comment] 2020-09-28 19:09
@mpanzica the Track data is actually being saved, it is literally just because the app is still running in the background. 

Pressing back does not actually destroy the application, just the view part of it. So, for example, if you start a task in the app ctor, it still lives around and can do things - for example, trigger an intent to launch an application..

When you are calling it again, there is actually a check it _is_ happening and it sees that it has already processed the variables, so it returns the currently running values in memory. Now is that a feature or a bug? tht is the question.

**Comment by mattleibow** [comment] 2020-09-28 19:12
In fact, I think the App instance from before the back is actually being leaked... @PureWeen might be able to help here...

**Closed** 2020-12-02 23:11 UTC
Labels: bug

**Comment by abubakrtaha** [comment] 2021-03-13 21:35
> @mpanzica the Track data is actually being saved, it is literally just because the app is still running in the background.
> 
> Pressing back does not actually destroy the application, just the view part of it. So, for example, if you start a task in the app ctor, it still lives around and can do things - for example, trigger an intent to launch an application..
> 
> When you are calling it again, there is actually a check it _is_ happening and it sees that it has already processed the variables, so it returns the currently running values in memory. Now is that a feature or a bug? tht is the question.

@mattleibow Why is this issue removed from 1.6.0 and closed? The problem is still not fixed neither as a feature nor as a bug
