### ISSUE TITLE
[Enhancement] Nigthly builds

### ISSUE THREAD

**Issue by VladislavAntonyuk** [xamarin/Essentials#1246] opened 2020-04-25 15:36 UTC
Xamarin.Forms has nightly builds. It would be nice to have the same for Xamarin.Essentials

**Comment by VladislavAntonyuk** [comment] 2020-04-25 15:45
in this case, we will not wait until all the APIs are combined and the full platform will be supported, but we will start using, for example, WebAuthenticator in WPF, while the Preferences are under development

**Comment by jamesmontemagno** [comment] 2020-04-28 17:35
Duplicate of #644

**Comment by jamesmontemagno** [comment] 2020-04-28 17:36
Every PR does have a nuget build attached to it.

For develop we will work on a nightly build.

**Closed by jamesmontemagno** 2020-04-28 17:35 UTC
Labels: feature-request
