### ISSUE TITLE
[Bug] ShareFile Not working as expected in iOS

### ISSUE THREAD

**Issue by sehuff** [xamarin/Essentials#982] opened 2019-11-12 17:48 UTC
Prior to iOS 13 the code below would show the user sharing dialog with apps that were relevant to the mime type. Now I have to click on the ... to even find the right app and when going back after the open/share, the Share pop up does not close as it use to. Here is the code:

`     
    
           Share.RequestAsync(new ShareFileRequest
            {
                Title = Title,                    
                File = new ShareFile(file, mimeType)
            });
`
The mimeType I'm passing for example is "application/vnd.openxmlformats-officedocument.wordprocessingml.document". Yet I have to click on More to find Word on iOS and after opening it the pop up does not go away as it did before iOS 13.

![image](https://user-images.githubusercontent.com/2104761/68696269-a1e3c880-054a-11ea-9887-ecf12acc613f.png)

**Comment by sehuff** [comment] 2019-12-09 15:13
Any update on this?  I hate to have to write native code to get around this but I'm not sure what else to do.

**Comment by jamesmontemagno** [comment] 2019-12-19 23:01
@sehuff do you have the code that you are using to get around it? would be good to compare.

**Comment by jamesmontemagno** [comment] 2020-01-03 19:58
I tested just passing in a docx with no mime type specified and it worked just fine and "copy to word" was there. I can confirm that the dialog stays there after sharing the box share sheet remains open, however this appears to be the correct funcationality. Go into "Files" select a pdf or some file and try to share to Notes. Notice the same behavior. If you share the file to Mail it will go away. Looks like an Apple bug: https://forums.developer.apple.com/thread/119482 closing out as it is working as intended by the OS.

**Closed by jamesmontemagno** 2020-01-03 19:58 UTC
Labels: bug
