### ISSUE TITLE
[Enhancement] Dialer expose if the device could make the call.

### ISSUE THREAD

**Issue by CliffAgius** [xamarin/Essentials#872] opened 2019-07-30 14:42 UTC
It would be nice if the Phone Dialer exposed a property maybe just a bool to indicate if the device could actually make the call.

There is already an Exception if the IsSupported returns false so make this a property so that it can be used to hide UI elements or change them based on the ability of the device to fulfil the Dial request.

Yes using DeviceInfo.Idiom can be checked but this isn't always correct, I have one device that has no sim card for example and there is the option that outbound calls are blocked.

I am happy to look at this but I know my use case is UI and @jamesmontemagno doesn't want to mix Essentials with UI elements at present.

**Comment by mattleibow** [comment] 2020-11-06 01:31
Duplicate of https://github.com/xamarin/Essentials/issues/77

**Closed** 2020-11-06 03:38 UTC
Labels: feature-request, needs-specifications, up-for-grabs
