### ISSUE TITLE
Email.ComposeAsync - Exception - UWP[Bug] 

### ISSUE THREAD

**Issue by cervesus** [xamarin/Essentials#889] opened 2019-08-22 11:51 UTC
### Description
Using "Email.ComposeAsync(message)" to send an email on UWP creates an exception. At first I thought the issue is related to #707 but I found out that the type of exception differs depending on the type of message to send. 

**1. Email with an attachment where the file ending has more or less than 3 characters (e.g. `*.md` or `*.json`):**
```
System.ArgumentException
  HResult=0x80070057
  Message=Value does not fall within the expected range.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Essentials.Email.<PlatformComposeAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at EmailTest.ViewModels.ItemsViewModel.<>c.<<-ctor>b__0_0>d.MoveNext() in C:\Users\myCoolUsername\source\repos\EmailTest\EmailTest\EmailTest\ViewModels\ItemsViewModel.cs:line 42
```

**2. Email without attachment or with an attachment where the file ending has 3 characters (e.g.: 
`*.txt`):**
```
System.ArgumentException
  HResult=0x80070057
  Message=The parameter is incorrect.

The parameter is incorrect.

  Source=System.Private.CoreLib
  StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Essentials.Email.<PlatformComposeAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at EmailTest.ViewModels.ItemsViewModel.<>c.<<-ctor>b__0_0>d.MoveNext() in C:\Users\myCoolUsername\source\repos\EmailTest\EmailTest\EmailTest\ViewModels\ItemsViewModel.cs:line 42
```

I've already checked if the file used for the attachment actually exists. It does.

### Steps to Reproduce
1. Enable Experimentalfeatures.
2. Try to send an email with Xamarin.Essentials in UWP - Please see attached Demo Solution.

### Demo Solution
[EmailTest.zip](https://github.com/xamarin/Essentials/files/3529923/EmailTest.zip)
I've only tested UWP.
### Expected Behavior
Email application opens.
### Actual Behavior
Exception gets thrown.

### Basic Information
- Version with issue: Xamarin.Forms 4.10555618
- Last known good version: uknown
- IDE: VS 2019 Enterprise, Version: 16.2.2
- Platform Target Frameworks: 
 - UWP:  16299
- Nuget Packages: 1.2.0 && 1.3.0-pre (both tested)
- Affected Devices: Desktop PC, Windows 10.0.17763

### Edit:
I've actually tested the same project on Android and iOS. It works on those platforms.

**Comment by newky2k** [comment] 2019-08-30 15:15
@cervesus  can you re-try with the full release and confirm if its still an issue.

Thanks

**Comment by cervesus** [comment] 2019-09-02 11:59
Unfortunately the problem still exists:

`   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Xamarin.Essentials.Email.<PlatformComposeAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at EmailTest.ViewModels.ItemsViewModel.<>c.<<-ctor>b__0_0>d.MoveNext() in C:\Users\MyCoolUserName\source\repos\EmailTest\EmailTest\EmailTest\ViewModels\ItemsViewModel.cs:line 48
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Threading.WinRTSynchronizationContextBase.Invoker.InvokeCore()`

**Comment by jamesmontemagno** [comment] 2019-10-13 05:11
I just tested this code on my Windows 10 machine and could not reproduce it with the same that was attached. I am running 1903 and the default mail app windows.

**Comment by jamesmontemagno** [comment] 2019-12-20 00:01
Closing as I am unable to reproduce.

**Closed by jamesmontemagno** 2019-12-20 00:01 UTC
Labels: bug, unable-to-reproduce, under-investigation
