### ISSUE TITLE
[Bug] - Android 12 - Geolocation.GetLocationAsync(request) throws an exception while coarse location is granted

### ISSUE THREAD

**Issue by aleksandarpanov** [xamarin/Essentials#2011] opened 2022-05-15 17:24 UTC
### Description
According to Android 12 documentation a user can grant only approximate location (ACCESS_COARSE_LOCATION) even while your app requests ACCESS_FINE_LOCATION.  When a geolocation request is made the app throws an exception stating that Permissions.LocationWhenInUse is not granted, although it doesn't have to be granted on Android 12 in order to get approximate location.

https://developer.android.com/training/location/permissions#approximate-request

### Steps to Reproduce

1. Request LocationWhenInUse permission.
2. Select Approximate precision in  a popup
3. Make a new geolocation request (any accuracy, any frequency)
4. The app throws an exception stating LocationWhenInUse is not granted.

### Expected Behavior
Code should use provided approximate location (ACCESS_CORASE_LOCATION) in order to pull a user's current location (as it is provided by Android 12)

I believe that code in line 259 of https://github.com/xamarin/Essentials/blob/e054b7e19b7fb8f1787af41c95ce4447660422ed/Xamarin.Essentials/Permissions/Permissions.android.cs#L259 should return PermissionStatus.Granted.

The issue is related to another bug reported a few days ago
[https://github.com/xamarin/Essentials/issues/2009](url)

### Actual Behavior
Code throws an exception stating that LocationWhenInUse is not provided.

### Basic Information

- Version with issue: 1.7.3
- Last known good version:
- IDE: VS 2022
- Platform Target Frameworks: 
  - iOS:  
  - Android: 12.2.4.3

**Comment by jfversluis** [comment] 2022-05-17 08:45
Duplicate of #2009

**Closed by jfversluis** 2022-05-17 08:45 UTC
Labels: bug
