### ISSUE TITLE
[Bug] MediaPicker (Capture photo) Error.

### ISSUE THREAD

**Issue by pulmuone** [xamarin/Essentials#1411] opened 2020-10-03 12:15 UTC
### Description
MediaPicker (Capture photo) Error. 
### Steps to Reproduce

1.  MediaPicker 
2. Capture photo
3.   Essentials-main\Essentials-ain\Xamarin.Essentials\Platform\Platform.android.cs
protected override void OnActivityResult(int requestCode, Result resultCode, Intent data)
...
                if (outputUri != null)
                        data.PutExtra(OutputUriExtra, outputUri); //data is null error.

### Basic Information

- Version with issue:
- Last known good version:
- IDE: VS2019
- Platform Target Frameworks: 
  - Android:  Android 10(API Leve 29 Q)

- Nuget Packages: 
- Affected Devices:

### Screenshots
![1111](https://user-images.githubusercontent.com/42885949/94991375-b9da9580-05bd-11eb-97ec-41de0d5c0081.jpg)

**Comment by pictos** [comment] 2020-10-03 14:03
@pulmuone can you attach a sample that reproduces the issue?

**Comment by pulmuone** [comment] 2020-10-04 00:28
https://github.com/xamarin/Essentials/tree/main/Samples

this sample

2020년 10월 3일 (토) 오후 11:03, Pedro Jesus <notifications@github.com>님이 작성:

**Comment by pulmuone** [comment] 2020-10-04 00:47
https://github.com/pulmuone/FilePickerTest
My Sample Source.

this menu "Capture photo" error .
**System.NullReferenceException:** 'Object reference not set to an instance
of an object.'

Test : VS 2019, Samsung Galaxy
20, Xamarin.Essentials 1.6.0-pre2, Xamarin.Forms 5.0.0.1487-pre1,



2020년 10월 4일 (일) 오전 9:28, 지현명 <pulmuone.ji@gmail.com>님이 작성:

**Comment by AdamDiament** [comment] 2020-10-11 11:49
The same thing happens for me on CaptureVideoAsync

**Comment by csmac3144** [comment] 2020-10-20 15:45
Using the vanilla Microsoft sample code. Crashes every time on both CapturePhotoAsync() and CaptureVideoAsync()
Null reference exception.
Using Xamarin Essentials: 1.6.0-pre2
Xamarin Forms: 5.0.0.1558-pre3

**Comment by msitsoftware** [comment] 2020-11-03 15:40
Same here. 
Xamarin.Essentials 1.6.0-pre2
Xamarin.Forms 4.6.0.1141

**Comment by AmrAlSayed0** [comment] 2020-11-03 15:48
Shouldn't this fix it? https://github.com/xamarin/Essentials/pull/1480

**Comment by msitsoftware** [comment] 2020-11-03 16:08
Thank you Amr. Works fine for me

**Comment by mattleibow** [comment] 2020-11-04 22:55
@msitsoftware from what I can understand, that PR fixed your issue?

Duplicate of #1397

**Closed by mattleibow** 2020-11-04 22:55 UTC
Labels: bug

**Comment by msitsoftware** [comment] 2020-11-05 07:43
@mattleibow I tried out #1480 and this works fine for me
