### ISSUE TITLE
[Bug] MediaPicker rotates images on Android and IOS, but not UWP

### ISSUE THREAD

**Issue by chrisevans9629** [xamarin/Essentials#1705] opened 2021-02-26 16:41 UTC
### Description
When taking an picture from the MediaPicker on android, it rotates the picture when read from a stream.
### Steps to Reproduce

1.  Create Xamarin.Forms empty template project
2.  Update nuget packages and follow the MediaPicker documentation [example](https://docs.microsoft.com/en-us/xamarin/essentials/media-picker?context=xamarin%2Fandroid&tabs=android)
3.  Add an image & button to the xaml and read the image source from bytes

```csharp
async Task LoadPhotoAsync(FileResult photo)
{
    // canceled
    if (photo == null)
    {
        PhotoPath = null;
        return;
    }
    // save the file into local storage
    var newFile = Path.Combine(FileSystem.CacheDirectory, photo.FileName);
    using (var stream = await photo.OpenReadAsync())
    using (var newStream = File.OpenWrite(newFile))
        await stream.CopyToAsync(newStream);

    PhotoPath = newFile;
    OnPropertyChanged(nameof(PhotoPath));
    // This works
    img.Source = ImageSource.FromFile(PhotoPath);

    // this gets an F for flipped
    //img.Source = ImageSource.FromStream(() => new MemoryStream(File.ReadAllBytes(PhotoPath)));
}
```

This is the line that doesn't work.  When you do this, it flips the image only on android.
```csharp
img.Source = ImageSource.FromStream(() => new MemoryStream(File.ReadAllBytes(PhotoPath)));
```
### Expected Behavior
The picture displayed should exactly match the picture taken
### Actual Behavior
The picture is rotated 90 degrees
### Basic Information

- Version with issue: 1.6.1
- Last known good version: NA
- IDE: Visual Studio
- Platform Target Frameworks: 
  - Android: 10.0
- Nuget Packages:
  - Xamarin.Essentials
- Affected Devices:
  - Galaxy S9
  - Galaxy Tab A

### Screenshots
This is what it should look like.  This image has not been rotated in other words.  This happens when you read the image from a file.
![Screenshot_20210226-102240](https://user-images.githubusercontent.com/33850520/109327930-7c053480-781e-11eb-9b48-8815ab39ae11.jpg)

This is what it should not look like.  This happens when reading the image from a byte stream.
![Screenshot_20210226-102314](https://user-images.githubusercontent.com/33850520/109327933-7d366180-781e-11eb-8370-c9a55ac3c409.jpg)

**Comment by egomadness** [comment] 2021-02-26 21:58
Yes, I noticed this today as well!!

**Comment by chrisevans9629** [comment] 2021-02-26 22:38
Yeah I am surprised no one else ran into this

**Comment by nicoriff** [comment] 2021-03-03 21:35
It happens the same to me but in iOS

**Comment by 21r8390** [comment] 2021-08-02 06:49
Me too!!! 😕

**Comment by dush135** [comment] 2021-12-13 05:22
any update?

**Comment by jfversluis** [comment] 2022-01-03 19:55
Duplicate of #1514

**Closed by jfversluis** 2022-01-03 19:55 UTC
Labels: bug
