### ISSUE TITLE
Geolocation: Add event for Location service state changed

### ISSUE THREAD

**Issue by craylward** [xamarin/Essentials#486] opened 2018-08-22 05:40 UTC
Same idea as Connectivity.ConnectivityChanged but for Location services enabled/disabled.

```
public event LocationServicesStateChangedEventHandler LocationServicesStateChanged
```

**Comment by jamesmontemagno** [comment] 2018-08-22 15:18
Duplicate of #290

**Closed by jamesmontemagno** 2018-08-22 15:18 UTC
